// Taxonomy and disclosures for the twenty two generator tools.
//
// The QR and link tools carry toolType "qr" and "link" so a search for "QR"
// returns the whole set, and so the tool-type filter is a real way to browse.
// The three that produce contract-adjacent wording carry the legal disclaimer.

import type { ToolMeta } from "../types";
import { ANY_BUSINESS, APPOINTMENT_DRIVEN, PHONE_DRIVEN, QUOTE_DRIVEN, merge } from "./shared";

const LOCAL_PUBLIC = merge(PHONE_DRIVEN, ["restaurant", "food-truck", "bar", "coffee-shop", "retail", "tourism", "vacation-rental", "hotel", "fitness", "church", "nonprofit", "event-venue", "k12-school", "government"]);

export const GENERATOR_META: Record<string, ToolMeta> = {
  "qr-code-maker": {
    domain: "websites-digital",
    toolType: "qr",
    goals: ["share-information", "create-marketing"],
    industries: merge(LOCAL_PUBLIC, ["printing", "photography", "creator-media", "wedding-services", "real-estate"]),
    audiences: ["owners", "managers", "creators", "administrators", "volunteers"],
    keywords: ["qr code", "scan", "printable code", "link to code", "flyer", "sign", "table tent", "vector qr"],
    synonyms: ["qr generator", "make a qr code", "barcode maker"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 96,
    seoTitle: "Free QR Code Maker with PNG and SVG download",
    seoDescription:
      "Turn any link into a scannable code. Pick the error correction and quiet zone, check the contrast, and download print ready PNG or SVG.",
    exportFormats: ["png", "svg", "print"],
    relatedSlugs: ["wifi-qr-code", "digital-business-card", "google-review-link", "utm-link-builder"],
  },

  "wifi-qr-code": {
    domain: "websites-digital",
    toolType: "qr",
    goals: ["share-information", "prepare-for-an-event"],
    industries: merge(["restaurant", "bar", "coffee-shop", "hotel", "vacation-rental", "coworking", "retail", "fitness", "event-venue", "church", "storage", "tourism"], APPOINTMENT_DRIVEN),
    audiences: ["owners", "managers", "administrators", "travelers"],
    keywords: ["wifi password", "guest network", "wifi qr", "network name", "ssid", "wpa", "guest wifi"],
    synonyms: ["wifi code generator", "guest wifi qr"],
    disclaimer: "general-estimate",
    dataSensitivity: "sensitive",
    popularity: 88,
    exportFormats: ["png", "svg", "print"],
    assumptions: ["The password is encoded into the code itself. Anyone who can photograph the sign has your network, so use a guest network."],
    relatedSlugs: ["qr-code-maker", "digital-business-card", "google-maps-link-generator", "google-review-link"],
  },

  "digital-business-card": {
    domain: "sales-marketing",
    toolType: "qr",
    goals: ["share-information", "capture-leads", "create-marketing"],
    industries: merge(PHONE_DRIVEN, ["consulting", "marketing-agency", "staffing", "creator-media", "photography", "chamber-business-org"]),
    audiences: ["owners", "salespeople", "professionals", "freelancers", "job-seekers"],
    keywords: ["vcard", "contact card", "digital card", "networking", "save my contact", "trade show", "business card qr"],
    synonyms: ["vcard qr generator", "digital business card qr"],
    disclaimer: "general-estimate",
    dataSensitivity: "personal",
    popularity: 85,
    exportFormats: ["png", "svg", "txt", "print"],
    relatedSlugs: ["qr-code-maker", "email-signature-generator", "click-to-call-button", "google-maps-link-generator"],
  },

  "click-to-call-button": {
    domain: "websites-digital",
    toolType: "link",
    goals: ["capture-leads", "share-information", "check-a-website"],
    industries: PHONE_DRIVEN,
    audiences: ["owners", "managers"],
    keywords: ["click to call", "tel link", "call button", "mobile call", "phone button", "html snippet", "tap to call"],
    synonyms: ["call button generator", "tel link builder"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 81,
    relatedSlugs: ["sms-link-generator", "mobile-traffic-loss", "missed-call-calculator", "digital-business-card"],
  },

  "sms-link-generator": {
    domain: "websites-digital",
    toolType: "link",
    goals: ["capture-leads", "improve-follow-up", "share-information"],
    industries: PHONE_DRIVEN,
    audiences: ["owners", "salespeople", "managers"],
    keywords: ["sms link", "text link", "click to text", "prefilled message", "sms href", "text us button"],
    synonyms: ["click to text generator", "text message link"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 79,
    relatedSlugs: ["click-to-call-button", "missed-call-textback-script", "digital-business-card", "review-request-script"],
  },

  "utm-link-builder": {
    domain: "sales-marketing",
    toolType: "link",
    goals: ["create-marketing", "make-a-decision", "check-a-website"],
    industries: merge(ANY_BUSINESS, ["marketing-agency", "creator-media"]),
    audiences: ["owners", "managers", "creators", "salespeople"],
    keywords: ["utm", "campaign tracking", "analytics", "source medium", "which ad worked", "tagged link", "attribution"],
    synonyms: ["utm builder", "campaign url builder", "tracking link generator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 83,
    relatedSlugs: ["roas-calculator", "qr-code-maker", "seo-traffic-value", "ad-budget-planner"],
  },

  "email-signature-generator": {
    domain: "sales-marketing",
    toolType: "generator",
    goals: ["create-marketing", "share-information", "capture-leads"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "salespeople", "administrators", "professionals"],
    keywords: ["email signature", "html signature", "sign off", "footer", "outlook signature", "gmail signature", "contact block"],
    synonyms: ["signature generator", "email footer builder"],
    disclaimer: "general-estimate",
    dataSensitivity: "personal",
    popularity: 78,
    relatedSlugs: ["digital-business-card", "google-review-link", "click-to-call-button", "review-request-script"],
  },

  "missed-call-textback-script": {
    domain: "sales-marketing",
    toolType: "generator",
    goals: ["improve-follow-up", "capture-leads", "make-money"],
    industries: PHONE_DRIVEN,
    audiences: ["owners", "managers", "administrators"],
    keywords: ["text back", "missed call automation", "auto reply", "sms script", "we missed you", "callback text", "after hours reply"],
    synonyms: ["missed call auto text", "text back script"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 87,
    assumptions: ["Automated texts to customers are regulated. Get consent, honour STOP, and check your carrier's rules before you turn one on."],
    relatedSlugs: ["missed-call-calculator", "after-hours-lead-calculator", "sms-link-generator", "voicemail-script-generator"],
  },

  "review-request-script": {
    domain: "sales-marketing",
    toolType: "generator",
    goals: ["create-marketing", "improve-follow-up"],
    industries: merge(PHONE_DRIVEN, ["restaurant", "retail", "fitness", "tourism", "vacation-rental", "photography", "wedding-services"]),
    audiences: ["owners", "managers", "administrators", "contractors"],
    keywords: ["ask for a review", "review request", "review text", "review email", "when to ask", "five star ask", "follow up message"],
    synonyms: ["how to ask for a review", "review ask script"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 84,
    assumptions: ["Never offer anything in exchange for a review. Most platforms remove them and some regulators treat it as deceptive."],
    relatedSlugs: ["google-review-link", "review-goal-calculator", "sms-link-generator", "review-response-writer"],
  },

  "estimate-terms-generator": {
    domain: "local-services",
    toolType: "template",
    goals: ["generate-a-document", "quote-a-job", "price-a-service"],
    industries: QUOTE_DRIVEN,
    audiences: ["owners", "contractors", "freelancers"],
    keywords: ["estimate terms", "deposit language", "quote validity", "change order", "scope", "warranty wording", "proposal terms"],
    synonyms: ["quote terms template", "deposit policy wording"],
    disclaimer: "legal",
    dataSensitivity: "none",
    popularity: 76,
    relatedSlugs: ["job-price-calculator", "late-payment-language", "cancellation-policy-generator", "payment-plan-calculator"],
  },

  "late-payment-language": {
    domain: "business-money",
    toolType: "template",
    goals: ["generate-a-document", "save-money", "improve-follow-up"],
    industries: merge(QUOTE_DRIVEN, ["consulting", "marketing-agency", "it-services", "accounting", "staffing", "printing", "manufacturing"]),
    audiences: ["owners", "administrators", "freelancers"],
    keywords: ["late fee", "invoice terms", "net 30", "payment terms", "collections wording", "early payment discount", "past due"],
    synonyms: ["invoice terms template", "late fee wording"],
    disclaimer: "legal",
    dataSensitivity: "none",
    popularity: 74,
    assumptions: ["Late fee limits are set by state law and by your contract. Confirm the rate you can actually charge before you send it."],
    relatedSlugs: ["late-invoice-calculator", "estimate-terms-generator", "payment-plan-calculator", "cancellation-policy-generator"],
  },

  "cancellation-policy-generator": {
    domain: "local-services",
    toolType: "template",
    goals: ["generate-a-document", "save-money", "prepare-for-an-event"],
    industries: merge(APPOINTMENT_DRIVEN, ["restaurant", "vacation-rental", "tourism", "event-venue", "wedding-services", "pet-services", "childcare"]),
    audiences: ["owners", "managers", "administrators", "professionals"],
    keywords: ["cancellation policy", "no show fee", "notice period", "deposit forfeit", "reschedule", "booking terms", "grace period"],
    synonyms: ["no show policy template", "booking cancellation wording"],
    disclaimer: "legal",
    dataSensitivity: "none",
    popularity: 77,
    assumptions: ["A fee you never told the customer about in advance is very hard to collect. Put this where they agree to it before booking."],
    relatedSlugs: ["no-show-calculator", "estimate-terms-generator", "late-payment-language", "payment-plan-calculator"],
  },

  "localbusiness-schema-generator": {
    domain: "websites-digital",
    toolType: "generator",
    goals: ["check-a-website", "create-marketing", "share-information"],
    industries: LOCAL_PUBLIC,
    audiences: ["owners", "managers"],
    keywords: ["schema markup", "structured data", "json ld", "local business", "rich results", "nap", "google listing code"],
    synonyms: ["localbusiness json ld", "structured data generator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 72,
    relatedSlugs: ["faq-schema-generator", "google-business-profile-scorecard", "meta-title-description-writer", "website-grader"],
  },

  "faq-schema-generator": {
    domain: "websites-digital",
    toolType: "generator",
    goals: ["check-a-website", "create-marketing"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers", "creators"],
    keywords: ["faq schema", "structured data", "json ld", "rich snippet", "questions markup", "seo code", "faqpage"],
    synonyms: ["faqpage json ld", "faq structured data"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 68,
    assumptions: ["Only mark up questions that are actually visible on the page. Hidden FAQ markup is a manual action waiting to happen."],
    relatedSlugs: ["localbusiness-schema-generator", "meta-title-description-writer", "website-grader", "seo-traffic-value"],
  },

  "meta-title-description-writer": {
    domain: "websites-digital",
    toolType: "generator",
    goals: ["create-marketing", "check-a-website"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers", "creators"],
    keywords: ["meta title", "meta description", "serp snippet", "title tag", "click through rate", "page title", "search listing"],
    synonyms: ["title tag writer", "serp preview generator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 75,
    relatedSlugs: ["seo-traffic-value", "faq-schema-generator", "localbusiness-schema-generator", "ad-character-counter"],
  },

  "ad-character-counter": {
    domain: "sales-marketing",
    toolType: "checker",
    goals: ["create-marketing", "check-a-website"],
    industries: merge(ANY_BUSINESS, ["marketing-agency", "creator-media"]),
    audiences: ["owners", "managers", "creators", "salespeople"],
    keywords: ["character count", "ad copy length", "headline limit", "truncation", "google ads", "meta ads", "character limit"],
    synonyms: ["ad copy length checker", "headline character counter"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 66,
    assumptions: ["Platform limits change. These are the current common limits, so check the ad manager before a big launch."],
    relatedSlugs: ["meta-title-description-writer", "google-post-writer", "ad-budget-planner", "job-post-writer"],
  },

  "google-maps-link-generator": {
    domain: "websites-digital",
    toolType: "link",
    goals: ["share-information", "capture-leads"],
    industries: LOCAL_PUBLIC,
    audiences: ["owners", "managers", "administrators", "travelers"],
    keywords: ["directions link", "google maps", "navigate to us", "address link", "find us", "map button", "drive here"],
    synonyms: ["directions button generator", "maps link builder"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 71,
    relatedSlugs: ["qr-code-maker", "click-to-call-button", "google-business-profile-scorecard", "digital-business-card"],
  },

  "add-to-calendar-link": {
    domain: "websites-digital",
    toolType: "link",
    goals: ["prepare-for-an-event", "share-information", "improve-follow-up"],
    industries: merge(["event-venue", "church", "nonprofit", "k12-school", "higher-education", "tourism", "fitness", "chamber-business-org", "government"], APPOINTMENT_DRIVEN),
    audiences: ["owners", "administrators", "volunteers", "teachers", "managers"],
    keywords: ["add to calendar", "ics file", "event link", "google calendar", "outlook invite", "save the date", "reminder"],
    synonyms: ["calendar link generator", "ics generator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 70,
    exportFormats: ["ics", "txt"],
    relatedSlugs: ["qr-code-maker", "no-show-calculator", "google-maps-link-generator", "sms-link-generator"],
  },

  "voicemail-script-generator": {
    domain: "sales-marketing",
    toolType: "generator",
    goals: ["improve-follow-up", "capture-leads", "generate-a-document"],
    industries: PHONE_DRIVEN,
    audiences: ["owners", "administrators", "managers"],
    keywords: ["voicemail greeting", "phone greeting", "answering message", "out of office", "call routing", "after hours message", "phone script"],
    synonyms: ["voicemail greeting writer", "business answering message"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 69,
    relatedSlugs: ["missed-call-textback-script", "missed-call-calculator", "after-hours-lead-calculator", "sms-link-generator"],
  },

  "job-post-writer": {
    domain: "business-money",
    toolType: "generator",
    goals: ["generate-a-document", "create-marketing", "plan-a-project"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers", "administrators"],
    keywords: ["job posting", "hiring ad", "job description", "recruiting", "help wanted", "indeed", "pay range"],
    synonyms: ["hiring ad writer", "job description generator"],
    disclaimer: "legal",
    dataSensitivity: "none",
    popularity: 73,
    assumptions: ["Several states require a pay range in the posting, and job ads are subject to equal opportunity rules. Check yours before you publish."],
    relatedSlugs: ["employee-true-cost", "hire-vs-automate", "overtime-cost-calculator", "ad-character-counter"],
  },

  "google-post-writer": {
    domain: "sales-marketing",
    toolType: "generator",
    goals: ["create-marketing", "capture-leads"],
    industries: LOCAL_PUBLIC,
    audiences: ["owners", "managers", "administrators"],
    keywords: ["google business post", "gbp post", "local update", "offer post", "seasonal promotion", "free listing", "what to post"],
    synonyms: ["google my business post writer", "gbp update generator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 71,
    relatedSlugs: ["google-business-profile-scorecard", "google-review-link", "meta-title-description-writer", "ad-character-counter"],
  },

  "robots-txt-generator": {
    domain: "websites-digital",
    toolType: "generator",
    goals: ["check-a-website", "organize-information"],
    industries: merge(ANY_BUSINESS, ["it-services", "saas", "app-development"]),
    audiences: ["owners", "managers"],
    keywords: ["robots txt", "crawler", "disallow", "sitemap directive", "search engine access", "indexing", "user agent"],
    synonyms: ["robots file generator", "crawler rules generator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 60,
    assumptions: ["robots.txt asks crawlers not to read a page. It does not hide it and it is not security. Anything private needs a real login."],
    relatedSlugs: ["localbusiness-schema-generator", "website-grader", "seo-traffic-value", "faq-schema-generator"],
  },
};
