// Taxonomy and disclosures for the eleven reputation and website tools.

import type { ToolMeta } from "../types";
import { ADVERTISERS, ANY_BUSINESS, APPOINTMENT_DRIVEN, PHONE_DRIVEN, merge } from "./shared";

/** Anyone whose customers look them up before calling, which is everyone local. */
const REVIEWED = merge(PHONE_DRIVEN, ["restaurant", "food-truck", "bar", "coffee-shop", "retail", "fitness", "tourism", "vacation-rental", "hotel", "wedding-services", "photography", "funeral-services", "childcare", "storage"]);

export const GROWTH_META: Record<string, ToolMeta> = {
  "google-review-link": {
    domain: "sales-marketing",
    toolType: "qr",
    goals: ["create-marketing", "share-information", "make-money"],
    industries: REVIEWED,
    audiences: ["owners", "managers", "administrators"],
    keywords: ["google review link", "review qr code", "place id", "leave us a review", "review card", "star rating", "review request"],
    synonyms: ["review link generator", "google review qr", "review shortcut"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 93,
    seoTitle: "Google Review Link and QR Code Maker",
    seoDescription:
      "Turn your business into a one tap review link and a printable QR code for the counter, the invoice and the truck.",
    relatedSlugs: ["review-request-script", "review-goal-calculator", "review-response-writer", "qr-code-maker"],
  },

  "review-goal-calculator": {
    domain: "sales-marketing",
    toolType: "planner",
    goals: ["plan-a-project", "create-marketing", "make-money"],
    industries: REVIEWED,
    audiences: ["owners", "managers"],
    keywords: ["star rating", "review goal", "average rating", "how many reviews", "reputation repair", "rating math", "ask rate"],
    synonyms: ["star rating calculator", "how many reviews to raise my rating"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 78,
    assumptions: ["Assumes new reviews come in at five stars, which is the best case, so treat the timeline as a floor."],
    relatedSlugs: ["google-review-link", "review-request-script", "bad-review-impact", "google-business-profile-scorecard"],
    presets: [
      { id: "restaurant", label: "Restaurant", industry: "restaurant", blurb: "High review volume and a rating customers actually filter on.", values: { current: 4.2, total: 340, goal: 4.5, perMonth: 12, asked: 300 } },
      { id: "trades", label: "Home services", industry: "hvac", blurb: "Fewer reviews, so each one moves the number a lot.", values: { current: 4.4, total: 38, goal: 4.8, perMonth: 3, asked: 45 } },
      { id: "dental", label: "Dental practice", industry: "dental-practice", blurb: "Steady patient flow makes a consistent ask easy.", values: { current: 4.6, total: 120, goal: 4.9, perMonth: 6, asked: 160 } },
      { id: "auto", label: "Auto repair", industry: "auto-repair", blurb: "Plenty of tickets, and a bad rating costs you the tow-in work.", values: { current: 4.1, total: 95, goal: 4.6, perMonth: 8, asked: 180 } },
    ],
  },

  "bad-review-impact": {
    domain: "sales-marketing",
    toolType: "calculator",
    goals: ["save-money", "make-a-decision", "create-marketing"],
    industries: REVIEWED,
    audiences: ["owners", "managers"],
    keywords: ["bad review", "one star", "negative review", "reputation damage", "rating drop", "lost customers", "review recovery"],
    synonyms: ["negative review cost", "what does a bad review cost"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 76,
    assumptions: ["The link between rating and enquiry volume is modelled from your own numbers, not from an industry study."],
    relatedSlugs: ["review-response-writer", "review-goal-calculator", "google-review-link", "review-request-script"],
  },

  "review-response-writer": {
    domain: "sales-marketing",
    toolType: "generator",
    goals: ["create-marketing", "improve-follow-up", "generate-a-document"],
    industries: REVIEWED,
    audiences: ["owners", "managers", "administrators"],
    keywords: ["review response", "reply to a review", "negative review reply", "reputation management", "apology", "thank you reply", "public response"],
    synonyms: ["how to respond to a bad review", "review reply generator"],
    disclaimer: "draft-document",
    dataSensitivity: "none",
    popularity: 82,
    assumptions: ["Read it before you post it. A response that sounds like a form letter does more damage than silence."],
    relatedSlugs: ["bad-review-impact", "google-review-link", "review-request-script", "review-goal-calculator"],
  },

  "website-speed-money": {
    domain: "websites-digital",
    toolType: "calculator",
    goals: ["check-a-website", "make-money", "save-money"],
    industries: ADVERTISERS,
    audiences: ["owners", "managers"],
    keywords: ["page speed", "slow website", "load time", "bounce rate", "core web vitals", "conversion loss", "hosting"],
    synonyms: ["site speed cost", "slow site calculator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 80,
    assumptions: ["Uses a conversion penalty that grows with load time. Your real curve depends on your audience and your offer."],
    relatedSlugs: ["mobile-traffic-loss", "conversion-lift-calculator", "website-grader", "downtime-cost-calculator"],
  },

  "conversion-lift-calculator": {
    domain: "websites-digital",
    toolType: "calculator",
    goals: ["check-a-website", "make-money", "capture-leads"],
    industries: ADVERTISERS,
    audiences: ["owners", "managers"],
    keywords: ["conversion rate", "cro", "one more percent", "landing page", "form completion", "split test", "traffic value"],
    synonyms: ["conversion rate calculator", "what is a percent worth"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 77,
    relatedSlugs: ["form-friction-calculator", "website-speed-money", "mobile-traffic-loss", "ad-test-budget-calculator"],
  },

  "mobile-traffic-loss": {
    domain: "websites-digital",
    toolType: "calculator",
    goals: ["check-a-website", "make-money", "capture-leads"],
    industries: ADVERTISERS,
    audiences: ["owners", "managers"],
    keywords: ["mobile", "phone traffic", "responsive", "mobile conversion gap", "thumb", "small screen", "mobile first"],
    synonyms: ["mobile conversion calculator", "phone visitor loss"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 73,
    relatedSlugs: ["website-speed-money", "conversion-lift-calculator", "click-to-call-button", "website-grader"],
  },

  "seo-traffic-value": {
    domain: "websites-digital",
    toolType: "calculator",
    goals: ["check-a-website", "make-money", "make-a-decision"],
    industries: ADVERTISERS,
    audiences: ["owners", "managers"],
    keywords: ["seo value", "organic traffic", "rankings", "cost per click equivalent", "search visibility", "keyword value", "google traffic"],
    synonyms: ["what is my seo worth", "organic traffic value"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 74,
    assumptions: ["Values organic visits at what the same clicks would cost in paid search, which is a proxy, not a market price."],
    relatedSlugs: ["meta-title-description-writer", "google-business-profile-scorecard", "website-grader", "conversion-lift-calculator"],
  },

  "website-grader": {
    domain: "websites-digital",
    toolType: "scorecard",
    goals: ["check-a-website", "make-a-decision", "capture-leads"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers"],
    keywords: ["website audit", "site checklist", "score my website", "conversion checklist", "web presence", "site review", "what is missing"],
    synonyms: ["website scorecard", "site audit checklist"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 86,
    relatedSlugs: ["google-business-profile-scorecard", "form-friction-calculator", "website-speed-money", "mobile-traffic-loss"],
  },

  "google-business-profile-scorecard": {
    domain: "websites-digital",
    toolType: "scorecard",
    goals: ["check-a-website", "capture-leads", "create-marketing"],
    industries: REVIEWED,
    audiences: ["owners", "managers", "administrators"],
    keywords: ["google business profile", "gbp", "google my business", "map pack", "local seo", "listing", "local pack", "nap"],
    synonyms: ["google my business checklist", "map listing audit"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 84,
    relatedSlugs: ["google-review-link", "google-post-writer", "localbusiness-schema-generator", "website-grader"],
  },

  "form-friction-calculator": {
    domain: "websites-digital",
    toolType: "calculator",
    goals: ["capture-leads", "check-a-website", "make-money"],
    industries: merge(ADVERTISERS, APPOINTMENT_DRIVEN),
    audiences: ["owners", "managers"],
    keywords: ["form fields", "friction", "abandonment", "contact form", "lead form", "fewer fields", "completion rate", "intake form"],
    synonyms: ["form abandonment calculator", "how many form fields"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 75,
    assumptions: ["Each extra field is modelled as a fixed drop in completion. Real forms vary by what you are asking for."],
    relatedSlugs: ["conversion-lift-calculator", "lead-response-time", "mobile-traffic-loss", "website-grader"],
  },
};
