// Taxonomy, presets and disclosures for the eighteen money tools.
// See lib/tools/meta/leads.ts for the pattern and docs/TOOLS_ARCHITECTURE.md for
// what each field means.

import type { ToolMeta } from "../types";
import { ANY_BUSINESS, APPOINTMENT_DRIVEN, QUOTE_DRIVEN, merge } from "./shared";

export const MONEY_META: Record<string, ToolMeta> = {
  "hourly-rate-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["price-a-service", "make-money"],
    industries: merge(QUOTE_DRIVEN, ["consulting", "photography", "it-services", "accounting", "massage", "tutoring"]),
    audiences: ["owners", "freelancers", "contractors", "professionals"],
    keywords: ["hourly rate", "shop rate", "billable hours", "what to charge", "rate setting", "underpricing", "overhead recovery", "day rate"],
    synonyms: ["what should I charge per hour", "shop rate calculator", "billable rate"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 94,
    seoTitle: "True Hourly Rate Calculator: what you actually have to charge",
    seoDescription:
      "Work back from the money you need to take home, your overhead and the hours you can really bill, to the rate that gets you there.",
    assumptions: [
      "Only billable hours earn. Admin, driving and quoting are treated as unpaid overhead.",
      "Tax is applied as a flat share of profit, which is a planning approximation, not a return.",
    ],
    relatedSlugs: ["job-price-calculator", "owner-hourly-worth", "profit-margin-calculator", "break-even-calculator"],
    presets: [
      { id: "trades", label: "Trades and home services", industry: "general-contracting", blurb: "Real billable time is well under half the week once driving and quoting are counted.", values: { take: 90000, overhead: 36000, weeks: 48, hours: 50, billable: 55, tax: 25, current: 95 } },
      { id: "consulting", label: "Consultant or coach", industry: "consulting", blurb: "High rate, low utilisation, and selling takes real hours.", values: { take: 120000, overhead: 18000, weeks: 46, hours: 40, billable: 50, tax: 30, current: 150 } },
      { id: "photography", label: "Photographer", industry: "photography", blurb: "Shooting is a fraction of the job. Editing and admin eat the rest.", values: { take: 65000, overhead: 20000, weeks: 48, hours: 45, billable: 35, tax: 25, current: 125 } },
      { id: "cleaning", label: "Cleaning company", industry: "cleaning", blurb: "High utilisation, thin overhead, and rate pressure from every direction.", values: { take: 70000, overhead: 22000, weeks: 50, hours: 45, billable: 75, tax: 22, current: 45 } },
      { id: "massage", label: "Massage or bodywork", industry: "massage", blurb: "There is a hard ceiling on hands-on hours in a week.", values: { take: 60000, overhead: 14000, weeks: 48, hours: 35, billable: 60, tax: 22, current: 90 } },
    ],
  },

  "job-price-calculator": {
    domain: "local-services",
    toolType: "estimator",
    goals: ["quote-a-job", "price-a-service", "make-money"],
    industries: QUOTE_DRIVEN,
    audiences: ["owners", "contractors", "salespeople"],
    keywords: ["job pricing", "bid", "estimate", "quote", "materials and labor", "markup", "waste factor", "drive time"],
    synonyms: ["bid calculator", "estimate builder", "how much to charge for a job"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 91,
    seoTitle: "Job Price Calculator: quote a job without guessing",
    seoDescription:
      "Materials, waste, labor, drive time, overhead and profit, added up into a price you can defend.",
    assumptions: [
      "Overhead and profit are applied to the full job cost, not to labor alone.",
      "Waste is applied to materials only.",
    ],
    relatedSlugs: ["hourly-rate-calculator", "markup-vs-margin", "estimate-terms-generator", "quote-follow-up-calculator"],
    presets: [
      { id: "roofing", label: "Roofing", industry: "roofing", blurb: "Material heavy, crew heavy, and waste is real on a cut-up roof.", values: { materials: 6200, waste: 12, hours: 40, laborCost: 34, drive: 2, overhead: 16, profit: 18 } },
      { id: "painting", label: "Painting", industry: "painting", blurb: "Labor is most of the job and materials are a small share.", values: { materials: 700, waste: 6, hours: 48, laborCost: 30, drive: 3, overhead: 18, profit: 22 } },
      { id: "plumbing", label: "Plumbing service call", industry: "plumbing", blurb: "Short jobs where drive time is a big part of the day.", values: { materials: 180, waste: 5, hours: 3, laborCost: 42, drive: 2, overhead: 22, profit: 25 } },
      { id: "landscaping", label: "Landscaping install", industry: "landscaping", blurb: "Heavy materials, plenty of waste, and a lot of hauling.", values: { materials: 2400, waste: 15, hours: 32, laborCost: 26, drive: 4, overhead: 18, profit: 20 } },
      { id: "remodel", label: "Kitchen or bath remodel", industry: "remodeling", blurb: "Long jobs where a thin margin will not survive one surprise.", values: { materials: 14000, waste: 10, hours: 160, laborCost: 40, drive: 3, overhead: 20, profit: 22 } },
      { id: "cleaning", label: "Commercial cleaning", industry: "cleaning", blurb: "Almost pure labor, priced by the hour against a route.", values: { materials: 90, waste: 0, hours: 6, laborCost: 20, drive: 2, overhead: 25, profit: 20 } },
    ],
  },

  "profit-margin-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["make-money", "price-a-service"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers", "salespeople"],
    keywords: ["profit margin", "gross margin", "markup", "cost of goods", "unit economics", "gross profit", "margin percentage"],
    synonyms: ["margin calculator", "gross profit calculator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 89,
    assumptions: ["Cost means the direct cost of delivering that unit, not your whole overhead."],
    relatedSlugs: ["markup-vs-margin", "job-price-calculator", "discount-damage-calculator", "break-even-calculator"],
    presets: [
      { id: "restaurant", label: "Restaurant plate", industry: "restaurant", blurb: "Food cost around 30 percent is the number kitchens run against.", values: { cost: 6, price: 20, target: 70, units: 400 } },
      { id: "retail", label: "Retail product", industry: "retail", blurb: "Keystone pricing, doubled from wholesale.", values: { cost: 22, price: 45, target: 50, units: 150 } },
      { id: "ecommerce", label: "Ecommerce order", industry: "ecommerce", blurb: "Product plus shipping and packing, before ad spend.", values: { cost: 18, price: 49, target: 60, units: 300 } },
      { id: "trades", label: "Service job", industry: "hvac", blurb: "Materials and crew against the quoted price.", values: { cost: 480, price: 900, target: 45, units: 25 } },
    ],
  },

  "markup-vs-margin": {
    domain: "business-money",
    toolType: "converter",
    goals: ["price-a-service", "make-money"],
    industries: merge(QUOTE_DRIVEN, ["retail", "ecommerce", "restaurant", "auto-repair", "construction-supply", "manufacturing"]),
    audiences: ["owners", "contractors", "managers"],
    keywords: ["markup", "margin", "gross profit", "cost plus", "pricing mistake", "multiplier", "50 percent markup"],
    synonyms: ["markup to margin converter", "margin vs markup"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 86,
    assumptions: ["Markup is measured on cost. Margin is measured on the selling price. They are never the same number."],
    relatedSlugs: ["profit-margin-calculator", "job-price-calculator", "discount-damage-calculator", "hourly-rate-calculator"],
  },

  "break-even-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["make-a-decision", "make-money", "plan-a-project"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers"],
    keywords: ["break even", "fixed costs", "keep the doors open", "monthly nut", "minimum sales", "contribution margin", "survival number"],
    synonyms: ["break even point", "how much do I need to sell"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 85,
    assumptions: ["Fixed costs are treated as fixed, which stops being true if volume changes a lot."],
    relatedSlugs: ["cash-runway-calculator", "profit-margin-calculator", "lead-goal-planner", "rent-receipt"],
    presets: [
      { id: "restaurant", label: "Restaurant", industry: "restaurant", blurb: "High fixed cost, small ticket, thin margin, open most days.", values: { fixed: 42000, ticket: 32, margin: 65, days: 28, actual: 120 } },
      { id: "salon", label: "Salon", industry: "hair-salon", blurb: "Rent and stylists fixed, service revenue variable.", values: { fixed: 14000, ticket: 85, margin: 55, days: 24, actual: 22 } },
      { id: "trades", label: "Trades company", industry: "hvac", blurb: "Trucks, insurance and a small office against a larger ticket.", values: { fixed: 22000, ticket: 850, margin: 45, days: 22, actual: 4 } },
      { id: "gym", label: "Gym or studio", industry: "fitness", blurb: "Rent dominates, memberships are the recurring ticket.", values: { fixed: 18000, ticket: 89, margin: 80, days: 30, actual: 12 } },
    ],
  },

  "price-increase-impact": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["make-money", "price-a-service", "make-a-decision"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers"],
    keywords: ["raise prices", "price increase", "churn", "customer loss", "pricing power", "inflation", "rate increase"],
    synonyms: ["should I raise my prices", "price rise calculator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 83,
    assumptions: ["Customers lost are assumed to leave immediately, which is the pessimistic case."],
    relatedSlugs: ["discount-damage-calculator", "profit-margin-calculator", "customer-lifetime-value", "markup-vs-margin"],
  },

  "discount-damage-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["save-money", "price-a-service", "make-a-decision"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "salespeople", "managers"],
    keywords: ["discount", "price cut", "coupon", "sale", "haggling", "volume to recover", "margin damage"],
    synonyms: ["what does a discount cost", "discount impact calculator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 80,
    assumptions: ["Assumes cost per unit stays flat as volume changes."],
    relatedSlugs: ["profit-margin-calculator", "price-increase-impact", "markup-vs-margin", "commission-calculator"],
  },

  "customer-lifetime-value": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["make-money", "make-a-decision", "capture-leads"],
    industries: merge(APPOINTMENT_DRIVEN, ["restaurant", "ecommerce", "retail", "saas", "fitness", "pet-services", "vacation-rental", "hvac", "landscaping", "pest-control", "cleaning"]),
    audiences: ["owners", "managers", "salespeople"],
    keywords: ["lifetime value", "ltv", "clv", "retention", "repeat business", "customer worth", "churn", "referrals"],
    synonyms: ["ltv calculator", "customer value calculator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 84,
    assumptions: [
      "Lifetime value here is gross profit, not revenue.",
      "Future value is not discounted for time, so treat long horizons as optimistic.",
    ],
    relatedSlugs: ["lead-value-calculator", "cac-payback-calculator", "cost-per-lead-calculator", "review-goal-calculator"],
    presets: [
      { id: "dental", label: "Dental patient", industry: "dental-practice", blurb: "Two visits a year for years, plus the family that follows.", values: { ticket: 220, visits: 2, years: 8, margin: 60, referrals: 1 } },
      { id: "salon", label: "Salon client", industry: "hair-salon", blurb: "Every six weeks, for as long as they like the stylist.", values: { ticket: 85, visits: 9, years: 4, margin: 55, referrals: 2 } },
      { id: "lawn", label: "Lawn or pest route", industry: "landscaping", blurb: "Recurring route work is the highest lifetime value in home services.", values: { ticket: 60, visits: 26, years: 5, margin: 50, referrals: 1 } },
      { id: "restaurant", label: "Restaurant regular", industry: "restaurant", blurb: "Small ticket, high frequency, and they bring people.", values: { ticket: 42, visits: 24, years: 4, margin: 65, referrals: 3 } },
      { id: "hvac", label: "HVAC customer", industry: "hvac", blurb: "Service visits between the two big replacement events.", values: { ticket: 380, visits: 2, years: 10, margin: 45, referrals: 1 } },
    ],
  },

  "payment-plan-calculator": {
    domain: "business-money",
    toolType: "builder",
    goals: ["make-money", "price-a-service", "generate-a-document"],
    industries: merge(QUOTE_DRIVEN, ["dental-practice", "legal", "auto-repair", "fitness", "wedding-services", "funeral-services", "tutoring"]),
    audiences: ["owners", "salespeople", "administrators"],
    keywords: ["payment plan", "deposit", "installments", "financing", "spread the cost", "down payment", "terms"],
    synonyms: ["installment calculator", "deposit and payments"],
    disclaimer: "financial",
    dataSensitivity: "none",
    popularity: 76,
    assumptions: [
      "This builds a simple in-house schedule. It is not a credit product and it does not compute APR.",
      "Any fee you add is treated as a flat percentage of the financed balance.",
    ],
    relatedSlugs: ["loan-payment-calculator", "job-price-calculator", "estimate-terms-generator", "late-invoice-calculator"],
  },

  "loan-payment-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["make-a-decision", "save-money", "plan-a-project"],
    industries: merge(QUOTE_DRIVEN, ["trucking", "logistics", "manufacturing", "agriculture", "ranching", "auto-repair", "restaurant", "mortgage-lending", "real-estate", "accounting", "financial-services"]),
    audiences: ["owners", "managers", "contractors"],
    keywords: ["loan payment", "amortization", "interest", "equipment finance", "monthly payment", "truck payment", "principal", "apr", "mortgage", "home loan", "refinance"],
    synonyms: ["monthly payment calculator", "amortization calculator", "equipment finance calculator", "mortgage payment calculator"],
    disclaimer: "financial",
    dataSensitivity: "none",
    popularity: 88,
    seoTitle: "Equipment and Loan Payment Calculator with total interest",
    seoDescription:
      "Monthly payment, total interest and whether the thing you are financing earns more than it costs.",
    assumptions: [
      "Standard fixed-rate amortization with equal monthly payments.",
      "No fees, insurance, taxes or balloon payments are included.",
    ],
    relatedSlugs: ["equipment-buy-vs-rent", "payment-plan-calculator", "cash-runway-calculator", "cost-per-mile-calculator"],
  },

  "late-invoice-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["save-money", "improve-follow-up", "make-money"],
    industries: merge(QUOTE_DRIVEN, ["consulting", "marketing-agency", "it-services", "accounting", "staffing", "manufacturing", "logistics", "printing"]),
    audiences: ["owners", "administrators", "managers"],
    keywords: ["accounts receivable", "unpaid invoices", "days sales outstanding", "dso", "chasing payment", "write off", "cash tied up", "net 30"],
    synonyms: ["accounts receivable calculator", "unpaid invoice cost"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 74,
    assumptions: ["The cost of tied-up cash is charged at the rate you enter, whether that is a line of credit or lost opportunity."],
    relatedSlugs: ["late-payment-language", "cash-runway-calculator", "payment-plan-calculator", "credit-card-fee-calculator"],
  },

  "cash-runway-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["make-a-decision", "save-money", "plan-a-project"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers"],
    keywords: ["runway", "burn rate", "months of cash", "survive", "cash flow", "reserves", "working capital"],
    synonyms: ["burn rate calculator", "how long will my cash last"],
    disclaimer: "financial",
    dataSensitivity: "none",
    popularity: 79,
    assumptions: ["Assumes this month repeats. A seasonal business should run it on a bad month, not an average one."],
    relatedSlugs: ["break-even-calculator", "late-invoice-calculator", "rent-receipt", "loan-payment-calculator"],
  },

  "sales-tax-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["generate-a-document", "organize-information", "make-money"],
    industries: merge(["retail", "ecommerce", "restaurant", "food-truck", "bar", "coffee-shop", "printing", "auto-repair", "construction-supply"], QUOTE_DRIVEN),
    audiences: ["owners", "administrators", "managers"],
    keywords: ["sales tax", "back out tax", "tax inclusive", "invoice tax", "gross to net", "tax rate", "add tax"],
    synonyms: ["tax calculator", "reverse sales tax"],
    disclaimer: "tax",
    dataSensitivity: "none",
    popularity: 77,
    assumptions: [
      "You supply the rate. This tool does not know your state, county or city rate, and never guesses one.",
      "It does not handle exemptions, tax holidays or multi-jurisdiction splits.",
    ],
    relatedSlugs: ["quarterly-tax-estimator", "profit-margin-calculator", "credit-card-fee-calculator", "job-price-calculator"],
  },

  "quarterly-tax-estimator": {
    domain: "business-money",
    toolType: "estimator",
    goals: ["save-money", "plan-a-project", "organize-information"],
    industries: merge(ANY_BUSINESS, ["personal-finance"]),
    audiences: ["owners", "freelancers", "contractors"],
    keywords: ["quarterly taxes", "estimated tax", "self employment tax", "set aside", "1099", "april surprise", "safe harbor"],
    synonyms: ["estimated tax calculator", "self employment tax set aside"],
    disclaimer: "tax",
    dataSensitivity: "personal",
    popularity: 81,
    assumptions: [
      "A flat planning rate, not a tax return. It ignores deductions, credits, filing status and state tax.",
      "Self-employment tax is applied on top of the income rate you choose.",
    ],
    relatedSlugs: ["mileage-deduction-calculator", "sales-tax-calculator", "cash-runway-calculator", "employee-true-cost"],
  },

  "mileage-deduction-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["save-money", "organize-information"],
    industries: merge(QUOTE_DRIVEN, ["real-estate", "mortgage-lending", "insurance", "trucking", "logistics", "consulting", "photography", "pet-services", "staffing"]),
    audiences: ["owners", "freelancers", "contractors", "salespeople"],
    keywords: ["mileage", "standard mileage rate", "vehicle deduction", "business miles", "mileage log", "irs rate", "write off"],
    synonyms: ["mileage write off calculator", "business mileage deduction"],
    disclaimer: "tax",
    dataSensitivity: "personal",
    popularity: 75,
    assumptions: [
      "You enter the mileage rate yourself. The rate changes and this tool never guesses it, so check the current IRS figure.",
      "The standard mileage method and the actual expense method are different elections. This models the standard rate only.",
    ],
    relatedSlugs: ["cost-per-mile-calculator", "quarterly-tax-estimator", "drive-time-cost", "sales-tax-calculator"],
  },

  "employee-true-cost": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["make-a-decision", "save-money", "plan-a-project"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers", "administrators"],
    keywords: ["labor burden", "true cost of an employee", "payroll tax", "workers comp", "benefits", "fully loaded cost", "hire cost"],
    synonyms: ["labor burden calculator", "cost of hiring someone"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 82,
    assumptions: [
      "Burden rates vary by state, trade and carrier. Use your own figures, not the defaults.",
      "Management time is charged at the rate you enter for your own hour.",
    ],
    relatedSlugs: ["hire-vs-automate", "overtime-cost-calculator", "hourly-rate-calculator", "capacity-calculator"],
  },

  "hire-vs-automate": {
    domain: "business-money",
    toolType: "scorecard",
    goals: ["make-a-decision", "save-time", "save-money"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers"],
    keywords: ["hire or automate", "software vs person", "payback", "headcount", "build vs hire", "operations decision"],
    synonyms: ["should I hire someone", "automate instead of hiring"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 72,
    assumptions: ["Assumes the system covers the share of the work you enter, and that the rest still needs a person."],
    relatedSlugs: ["task-automation-savings", "employee-true-cost", "admin-time-audit", "owner-hourly-worth"],
  },

  "overtime-cost-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["save-money", "make-a-decision", "plan-a-project"],
    industries: merge(ANY_BUSINESS, ["fire-ems", "law-enforcement", "public-safety", "private-security", "government"]),
    audiences: ["owners", "managers", "administrators", "public-servants"],
    keywords: ["overtime", "time and a half", "labor cost", "scheduling", "burden", "extra hours", "coverage cost"],
    synonyms: ["overtime vs new hire", "time and a half calculator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 78,
    assumptions: [
      "Overtime is calculated at one and a half times the base rate. Some states and contracts require more.",
      "This is a budgeting aid, not a wage and hour compliance check.",
    ],
    relatedSlugs: ["employee-true-cost", "capacity-calculator", "hire-vs-automate", "meeting-cost-calculator"],
  },
};
