// Taxonomy, presets and disclosures for the seventeen cost, ad and time tools.

import type { ToolMeta } from "../types";
import { ADVERTISERS, ANY_BUSINESS, QUOTE_DRIVEN, merge } from "./shared";

export const OPERATIONS_META: Record<string, ToolMeta> = {
  "rent-receipt": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["save-money", "make-a-decision"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers"],
    keywords: ["software subscriptions", "monthly fees", "saas stack", "recurring costs", "renting your platform", "tool sprawl", "subscription audit"],
    synonyms: ["subscription audit", "what am I paying every month", "software stack cost"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 87,
    seoTitle: "The Rent Receipt: what you pay every month just to exist online",
    seoDescription:
      "Add up the website, email, booking, CRM and review subscriptions, then see the ten year number with normal price rises.",
    assumptions: ["Assumes the annual increase you enter compounds every year on the whole stack."],
    relatedSlugs: ["per-seat-cost-calculator", "platform-fee-calculator", "cash-runway-calculator", "break-even-calculator"],
  },

  "credit-card-fee-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["save-money", "price-a-service"],
    industries: merge(["retail", "ecommerce", "restaurant", "food-truck", "bar", "coffee-shop", "hair-salon", "nail-salon", "barbershop", "spa", "auto-repair", "fitness", "vacation-rental", "tourism"], QUOTE_DRIVEN),
    audiences: ["owners", "managers", "administrators"],
    keywords: ["processing fees", "merchant fees", "interchange", "card rate", "per transaction", "surcharge", "payment processor"],
    synonyms: ["merchant fee calculator", "card processing cost"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 76,
    assumptions: ["Assumes a single blended rate. Real statements mix interchange, assessments and processor margin."],
    relatedSlugs: ["platform-fee-calculator", "profit-margin-calculator", "late-invoice-calculator", "rent-receipt"],
  },

  "platform-fee-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["save-money", "make-a-decision", "capture-leads"],
    industries: merge(["ecommerce", "retail", "vacation-rental", "hotel", "tourism", "restaurant", "creator-media", "photography", "pet-services", "moving"], QUOTE_DRIVEN),
    audiences: ["owners", "freelancers", "creators"],
    keywords: ["marketplace fees", "lead fees", "commission", "take rate", "third party platform", "direct booking", "middleman"],
    synonyms: ["marketplace fee calculator", "lead platform cost"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 79,
    assumptions: ["Repeat customers are counted as revenue you could have kept, which assumes you have a way to reach them directly."],
    relatedSlugs: ["rent-receipt", "credit-card-fee-calculator", "cost-per-lead-calculator", "lead-value-calculator"],
    presets: [
      { id: "airbnb", label: "Vacation rental", industry: "vacation-rental", blurb: "Platform commission on every night, on guests who often rebook.", values: { revenue: 6500, fee: 15, leadFees: 0, repeat: 25 } },
      { id: "food-delivery", label: "Restaurant delivery apps", industry: "restaurant", blurb: "Delivery platform commission is the highest take rate most owners pay.", values: { revenue: 9000, fee: 28, leadFees: 0, repeat: 55 } },
      { id: "trades-leads", label: "Home services lead apps", industry: "general-contracting", blurb: "Pay per lead, whether or not the lead answers.", values: { revenue: 14000, fee: 5, leadFees: 900, repeat: 35 } },
      { id: "etsy", label: "Online marketplace", industry: "ecommerce", blurb: "Listing plus transaction plus payment fees, on a small ticket.", values: { revenue: 5000, fee: 12, leadFees: 60, repeat: 30 } },
    ],
  },

  "per-seat-cost-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["save-money", "make-a-decision"],
    industries: merge(ANY_BUSINESS, ["it-services", "saas"]),
    audiences: ["owners", "managers", "administrators"],
    keywords: ["per seat pricing", "license cost", "software seats", "unused licenses", "ghost seats", "user based pricing", "growth penalty"],
    synonyms: ["seat license calculator", "per user pricing cost"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 70,
    assumptions: ["Assumes headcount grows at the rate you enter and every new person needs every tool."],
    relatedSlugs: ["rent-receipt", "employee-true-cost", "hire-vs-automate", "task-automation-savings"],
  },

  "downtime-cost-calculator": {
    domain: "websites-digital",
    toolType: "calculator",
    goals: ["save-money", "make-a-decision", "check-a-website"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers"],
    keywords: ["downtime", "outage", "website down", "phones down", "uptime", "hosting", "lost hours", "backup"],
    synonyms: ["outage cost calculator", "what does downtime cost"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 68,
    assumptions: ["Some business comes back after an outage. The recovery share you enter is what decides how much."],
    relatedSlugs: ["website-speed-money", "missed-call-calculator", "rent-receipt", "after-hours-lead-calculator"],
  },

  "equipment-buy-vs-rent": {
    domain: "local-services",
    toolType: "scorecard",
    goals: ["make-a-decision", "save-money"],
    industries: merge(QUOTE_DRIVEN, ["general-contracting", "concrete", "agriculture", "ranching", "manufacturing", "moving", "event-venue", "printing"]),
    audiences: ["owners", "contractors", "managers"],
    keywords: ["buy or rent", "equipment", "rental rate", "utilization", "resale value", "ownership cost", "break even days"],
    synonyms: ["rent or buy equipment", "equipment ownership calculator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 71,
    assumptions: [
      "Ownership cost includes upkeep and lost resale value, but not the interest on a loan. Run the loan tool for that.",
      "Assumes the machine is available when you need it, which is the real argument for owning.",
    ],
    relatedSlugs: ["loan-payment-calculator", "cost-per-mile-calculator", "capacity-calculator", "job-price-calculator"],
  },

  "roas-calculator": {
    domain: "sales-marketing",
    toolType: "calculator",
    goals: ["make-a-decision", "make-money", "save-money"],
    industries: ADVERTISERS,
    audiences: ["owners", "managers", "salespeople"],
    keywords: ["roas", "return on ad spend", "ad performance", "profitable ads", "break even roas", "ad waste", "attribution"],
    synonyms: ["return on ad spend calculator", "are my ads working"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 85,
    assumptions: [
      "Revenue attributed to the ad is taken at face value. Platform reported revenue is usually generous.",
      "Break-even ROAS is derived from your gross margin, not from revenue.",
    ],
    relatedSlugs: ["ad-budget-planner", "cost-per-lead-calculator", "cac-payback-calculator", "lead-value-calculator"],
  },

  "ad-budget-planner": {
    domain: "sales-marketing",
    toolType: "planner",
    goals: ["plan-a-project", "capture-leads", "make-money"],
    industries: ADVERTISERS,
    audiences: ["owners", "managers", "salespeople"],
    keywords: ["ad budget", "how much to spend", "media budget", "work backward", "lead target", "monthly spend", "marketing plan"],
    synonyms: ["marketing budget calculator", "how much should I spend on ads"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 83,
    assumptions: ["Assumes cost per lead holds as you scale spend, which it usually does not past a point."],
    relatedSlugs: ["roas-calculator", "cost-per-lead-calculator", "lead-goal-planner", "ad-test-budget-calculator"],
    presets: [
      { id: "roofing", label: "Roofer", industry: "roofing", blurb: "Expensive leads, large jobs, thin margins.", values: { want: 6, close: 25, cpl: 110, value: 9500, margin: 30 } },
      { id: "mortgage", label: "Mortgage lender", industry: "mortgage-lending", blurb: "Costly rate enquiries and a low funded rate.", values: { want: 8, close: 15, cpl: 130, value: 4200, margin: 90 } },
      { id: "dental", label: "Dental practice", industry: "dental-practice", blurb: "New patient acquisition against a long relationship.", values: { want: 25, close: 45, cpl: 70, value: 1200, margin: 60 } },
      { id: "hvac", label: "HVAC company", industry: "hvac", blurb: "Seasonal spend against service and replacement work.", values: { want: 40, close: 35, cpl: 55, value: 950, margin: 45 } },
      { id: "law", label: "Law firm", industry: "legal", blurb: "Few cases needed, high value, expensive clicks.", values: { want: 5, close: 25, cpl: 200, value: 3500, margin: 70 } },
    ],
  },

  "cac-payback-calculator": {
    domain: "sales-marketing",
    toolType: "calculator",
    goals: ["make-a-decision", "make-money"],
    industries: merge(["saas", "it-services", "fitness", "pest-control", "landscaping", "cleaning", "pool-service", "storage", "coworking"], ADVERTISERS),
    audiences: ["owners", "managers"],
    keywords: ["cac", "payback period", "customer acquisition cost", "months to recover", "churn", "recurring revenue", "unit economics"],
    synonyms: ["cac payback", "how long to recover acquisition cost"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 69,
    assumptions: ["Monthly value is treated as gross profit. Churn is applied evenly, not in cohorts."],
    relatedSlugs: ["customer-lifetime-value", "cost-per-lead-calculator", "roas-calculator", "lead-value-calculator"],
  },

  "ad-test-budget-calculator": {
    domain: "sales-marketing",
    toolType: "planner",
    goals: ["plan-a-project", "make-a-decision", "save-money"],
    industries: ADVERTISERS,
    audiences: ["owners", "managers", "creators"],
    keywords: ["ad testing", "test budget", "sample size", "statistical confidence", "split test", "variants", "learning phase"],
    synonyms: ["how much to spend testing ads", "ad test calculator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 62,
    assumptions: ["A useful read needs enough conversions per variant. Stopping early on a small sample is how people learn the wrong lesson."],
    relatedSlugs: ["ad-budget-planner", "roas-calculator", "conversion-lift-calculator", "cost-per-lead-calculator"],
  },

  "commission-calculator": {
    domain: "sales-marketing",
    toolType: "builder",
    goals: ["price-a-service", "make-a-decision", "make-money"],
    industries: merge(["real-estate", "mortgage-lending", "insurance", "auto-dealership", "saas", "staffing", "marketing-agency", "printing", "manufacturing"], QUOTE_DRIVEN),
    audiences: ["owners", "salespeople", "managers"],
    keywords: ["commission plan", "sales comp", "draw", "base plus commission", "margin based commission", "quota", "payout"],
    synonyms: ["sales commission plan builder", "commission structure calculator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 77,
    assumptions: ["Commission on revenue and commission on margin behave very differently when discounting starts. That is the point of the toggle."],
    relatedSlugs: ["close-rate-calculator", "discount-damage-calculator", "employee-true-cost", "profit-margin-calculator"],
    presets: [
      { id: "realtor", label: "Real estate team", industry: "real-estate", blurb: "Few closings, large tickets, split off gross commission.", values: { deals: 3, size: 9000, margin: 95, basis: "revenue", rate: 50, base: 0 } },
      { id: "mortgage", label: "Mortgage loan officer", industry: "mortgage-lending", blurb: "Basis points on funded volume, usually with a small base.", values: { deals: 6, size: 4200, margin: 90, basis: "revenue", rate: 40, base: 2000 } },
      { id: "auto", label: "Auto sales", industry: "auto-dealership", blurb: "Paid on gross, which is why discounting hurts the salesperson too.", values: { deals: 12, size: 2200, margin: 95, basis: "profit", rate: 25, base: 1800 } },
      { id: "trades", label: "In-home sales rep", industry: "roofing", blurb: "Margin based, so the rep cannot buy the deal with a discount.", values: { deals: 8, size: 9500, margin: 30, basis: "profit", rate: 12, base: 2500 } },
    ],
  },

  "admin-time-audit": {
    domain: "business-money",
    toolType: "checklist",
    goals: ["save-time", "save-money", "organize-information"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "administrators", "managers"],
    keywords: ["admin time", "paperwork", "busywork", "back office", "time audit", "delegation", "automation candidates"],
    synonyms: ["paperwork time calculator", "back office time audit"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 73,
    relatedSlugs: ["task-automation-savings", "owner-hourly-worth", "hire-vs-automate", "meeting-cost-calculator"],
  },

  "task-automation-savings": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["save-time", "save-money", "make-a-decision"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "managers", "administrators"],
    keywords: ["automation", "payback", "repetitive task", "manual process", "error cost", "worth automating", "build cost"],
    synonyms: ["automation payback calculator", "is this worth automating"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 72,
    assumptions: ["Assumes the automation keeps working. Budget for it breaking at least once a year."],
    relatedSlugs: ["admin-time-audit", "hire-vs-automate", "owner-hourly-worth", "per-seat-cost-calculator"],
  },

  "cost-per-mile-calculator": {
    domain: "local-services",
    toolType: "calculator",
    goals: ["price-a-service", "save-money", "quote-a-job"],
    industries: merge(["trucking", "logistics", "moving", "towing", "pet-services", "agriculture"], QUOTE_DRIVEN),
    audiences: ["owners", "contractors", "managers"],
    keywords: ["cost per mile", "vehicle cost", "fleet", "fuel", "depreciation", "truck expenses", "trip charge", "cpm"],
    synonyms: ["truck cost per mile", "vehicle operating cost"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 74,
    assumptions: ["Fixed costs are spread over the annual miles you enter. Drive fewer miles and the per mile number goes up."],
    relatedSlugs: ["drive-time-cost", "mileage-deduction-calculator", "equipment-buy-vs-rent", "job-price-calculator"],
  },

  "drive-time-cost": {
    domain: "local-services",
    toolType: "calculator",
    goals: ["save-time", "save-money", "price-a-service"],
    industries: merge(QUOTE_DRIVEN, ["pest-control", "pool-service", "pet-services", "home-health", "real-estate", "trucking", "moving"]),
    audiences: ["owners", "contractors", "managers"],
    keywords: ["drive time", "windshield time", "routing", "travel between jobs", "unbillable hours", "service radius", "dispatch"],
    synonyms: ["windshield time calculator", "travel time cost"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 67,
    relatedSlugs: ["cost-per-mile-calculator", "capacity-calculator", "job-price-calculator", "owner-hourly-worth"],
  },

  "meeting-cost-calculator": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["save-time", "save-money", "make-a-decision"],
    industries: merge(ANY_BUSINESS, ["government", "k12-school", "higher-education", "nonprofit", "church", "public-safety"]),
    audiences: ["owners", "managers", "administrators", "public-servants"],
    keywords: ["meeting cost", "recurring meeting", "standup", "wasted hours", "attendee cost", "agenda", "calendar bloat"],
    synonyms: ["what does this meeting cost", "meeting price calculator"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 75,
    assumptions: ["Counts loaded hourly cost, including the prep time before the meeting starts."],
    relatedSlugs: ["admin-time-audit", "owner-hourly-worth", "employee-true-cost", "overtime-cost-calculator"],
  },

  "owner-hourly-worth": {
    domain: "business-money",
    toolType: "calculator",
    goals: ["save-time", "make-a-decision", "make-money"],
    industries: ANY_BUSINESS,
    audiences: ["owners", "freelancers"],
    keywords: ["what your hour is worth", "opportunity cost", "delegation", "low value work", "stop doing list", "owner time", "effective rate"],
    synonyms: ["value of my time", "owner hourly rate"],
    disclaimer: "general-estimate",
    dataSensitivity: "none",
    popularity: 80,
    assumptions: ["Assumes the hours you free up go into work that actually earns, which is the hard part."],
    relatedSlugs: ["admin-time-audit", "hourly-rate-calculator", "hire-vs-automate", "meeting-cost-calculator"],
  },
};
