import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, before, beforeEach, describe, it } from "node:test";
import { createPictureTestDb } from "./helpers/picture-test-db.ts";
import { addAsset, adminAction, applyManualOutputs, approvePlan, authenticateOrder, claimJob, completeImage, completePlan, createOrder, databaseReady, failJob, getOrderInternal, heartbeatJob, packDefinition, rateLimit, recordPayment, recordProviderStarted, reserveSpend, reviewOrder, setPictureStorePoolForTests, stopPayment, updateBrief, workerHeartbeat, workerReady } from "../lib/pictureStudio/store.ts";
import { parseBrief, publicOrder, type PictureFile, type ScenePlan } from "../lib/pictureStudio/types.ts";

const brief = () => parseBrief({ audience: "personal", title: "Our next chapter", moment: "Family birthday", theme: "Original space adventure", emotion: "Hopeful", story: "Our family making new memories", assetsRights: true, subjectsConsent: true, usesLikeness: false });
const plans = (count: number): ScenePlan[] => Array.from({ length: count }, (_, index) => ({ index, title: `Scene ${index + 1}`, prompt: `Original cinematic composition ${index + 1}`, caption: "Our next chapter begins." }));
const files = (index: number): PictureFile[] => ["square", "portrait"].map(variant => ({ id: randomUUID(), path: `scene-${randomUUID()}.png`, filename: `scene-${index}-${variant}.png`, mime: "image/png", size: 100, sceneIndex: index, variant: variant as "square" | "portrait" }));
let database: Awaited<ReturnType<typeof createPictureTestDb>>;
let previousNodeEnv: string | undefined;
const testEnv = process.env as Record<string, string | undefined>;
async function makeOrder(packId = "starter", quantity = 1) {
  const result = await createOrder({ packId, quantity, email: "buyer@example.test", name: "A Family", brief: brief() });
  const sessionId = `cs_${randomUUID()}`;
  await database.pool.query("UPDATE picture_orders SET checkout_session_id=$2 WHERE id=$1", [result.id, sessionId]);
  await database.pool.query("INSERT INTO picture_checkout_sessions(id,order_id,attempt,expires_at) VALUES ($1,$2,1,now()+interval '24 hours')", [sessionId, result.id]);
  return { ...result, sessionId };
}
async function pay(order: Awaited<ReturnType<typeof makeOrder>>, overrides: Record<string, unknown> = {}) {
  const stored = await getOrderInternal(order.id), pack = packDefinition(stored.packId, stored.quantity);
  await recordPayment({ eventId: `evt_${order.sessionId}`, orderId: order.id, sessionId: order.sessionId, paymentIntent: `pi_${order.id}`, amountCents: pack.amountCents, priceId: pack.priceId, quantity: pack.quantity, currency: "usd", paid: true, livemode: true, ...overrides });
}
async function readyImages(order: Awaited<ReturnType<typeof makeOrder>>) {
  await pay(order); const job = await claimJob("test-worker"); assert.ok(job); assert.equal(job.job.kind, "plan");
  await completePlan(job.job.id, job.job.leaseToken, plans(job.order.pictureCount)); await approvePlan(order.id);
}
async function produceCollection(order: Awaited<ReturnType<typeof makeOrder>>, actualCostCents = 20) {
  await readyImages(order);
  for (let index = 0; index < 5; index++) {
    const next = await claimJob("test-worker"); assert.ok(next); await reserveSpend(next.job.id, next.job.leaseToken, 100); await recordProviderStarted(next.job.id, next.job.leaseToken);
    await completeImage(next.job.id, next.job.leaseToken, { files: files(next.job.sceneIndex!), providerRequestId: `request-${index}`, actualCostCents });
  }
  assert.equal((await getOrderInternal(order.id)).status, "owner_review");
  await adminAction(order.id, "release", "Reviewed all scenes.");
}

describe("durable picture studio state and payment boundaries", { concurrency: false }, () => {
  before(async () => { previousNodeEnv = testEnv.NODE_ENV; testEnv.NODE_ENV = "test"; database = await createPictureTestDb(); setPictureStorePoolForTests(database.pool); });
  beforeEach(async () => { await database.db.exec("TRUNCATE picture_audit,picture_spend,picture_jobs,picture_checkout_sessions,picture_orders,picture_events,picture_payment_stops,picture_rate_limits,picture_worker_health RESTART IDENTITY CASCADE"); delete process.env.PICTURE_DAILY_BUDGET_CENTS; });
  after(async () => { setPictureStorePoolForTests(undefined); if (previousNodeEnv === undefined) delete testEnv.NODE_ENV; else testEnv.NODE_ENV = previousNodeEnv; await database.close(); });
  it("checks the complete schema and fresh worker heartbeat", async () => { assert.equal(await databaseReady(), true); assert.equal(await workerReady(), false); await workerHeartbeat("unit-test"); assert.equal(await workerReady(), true); await database.pool.query("UPDATE picture_worker_health SET last_seen=now()-interval '3 minutes'"); assert.equal(await workerReady(), false); });
  it("hashes private access and rejects a different bearer", async () => { const order = await makeOrder(); assert.equal((await authenticateOrder(order.id, order.accessToken)).id, order.id); const row = await database.pool.query("SELECT access_hash FROM picture_orders WHERE id=$1", [order.id]); assert.notEqual(row.rows[0].access_hash, order.accessToken); await assert.rejects(authenticateOrder(order.id, "x".repeat(43)), /access is required/); });
  it("enforces 1–4 quantities only on the 30-picture pack", () => { assert.equal(packDefinition("daily", 4).pictureCount, 120); assert.equal(packDefinition("daily", 4).amountCents, 158800); assert.throws(() => packDefinition("starter", 2)); assert.equal(packDefinition("bulk100", 1).priceId, "price_1UNR9pBHH7tuNwAA3Mma4SO7"); });
  it("does not queue unpaid orders or accept an incomplete plan", async () => { const order = await makeOrder(); assert.equal(await claimJob("test-worker"), null); await assert.rejects(approvePlan(order.id), /successful payment/); await pay(order); const job = await claimJob("test-worker"); assert.ok(job); await assert.rejects(completePlan(job.job.id, job.job.leaseToken, plans(4)), /incomplete/); });
  it("rejects wrong amount, price, currency, quantity and unknown checkout before recording a paid event", async () => { const order = await makeOrder(); for (const bad of [{ amountCents: 1 }, { priceId: "wrong" }, { currency: "eur" }, { quantity: 2 }, { sessionId: "cs_unknown" }]) await assert.rejects(pay(order, bad)); assert.equal((await getOrderInternal(order.id)).paymentStatus, "unpaid"); assert.equal((await database.pool.query("SELECT count(*)::int AS n FROM picture_events")).rows[0].n, 0); });
  it("deduplicates payment and plan approval rather than creating extra pictures", async () => { const order = await makeOrder(); await readyImages(order); await pay(order); await approvePlan(order.id); const count = await database.pool.query("SELECT count(*)::int AS n FROM picture_jobs WHERE order_id=$1 AND kind='image'", [order.id]); assert.equal(count.rows[0].n, 5); });
  it("preserves a refund arriving before the paid checkout event", async () => { const order = await makeOrder(); await stopPayment({ eventId: "evt_refund_first", paymentIntent: `pi_${order.id}`, status: "refunded" }); await pay(order); assert.equal((await getOrderInternal(order.id)).paymentStatus, "refunded"); assert.equal(await claimJob("test-worker"), null); });
  it("accepts a delayed valid payment for an earlier checkout attempt", async () => { const order = await makeOrder(); await database.pool.query("UPDATE picture_orders SET checkout_session_id='cs_newer' WHERE id=$1", [order.id]); await pay(order); assert.equal((await getOrderInternal(order.id)).paymentStatus, "paid"); });
  it("ignores a newer async failure once an earlier valid checkout has paid", async () => { const order = await makeOrder(); await database.pool.query("UPDATE picture_orders SET checkout_session_id='cs_newer' WHERE id=$1", [order.id]); await pay(order); await stopPayment({ eventId: "evt_newer_failed", sessionId: "cs_newer", status: "failed" }); assert.equal((await getOrderInternal(order.id)).status, "planning"); assert.equal((await getOrderInternal(order.id)).paymentStatus, "paid"); assert.ok(await claimJob("test-worker")); });
  it("prevents provider calls without a reservation, after pause, and after dispute", async () => { const order = await makeOrder(); await readyImages(order); const next = await claimJob("test-worker"); assert.ok(next); await assert.rejects(recordProviderStarted(next.job.id, next.job.leaseToken), /Reserve/); await reserveSpend(next.job.id, next.job.leaseToken, 100); await adminAction(order.id, "pause", "Review"); await assert.rejects(recordProviderStarted(next.job.id, next.job.leaseToken), /paused/); await stopPayment({ eventId: "evt_dispute", paymentIntent: `pi_${order.id}`, status: "disputed" }); assert.equal((await getOrderInternal(order.id)).status, "disputed"); await assert.rejects(completeImage(next.job.id, next.job.leaseToken, { files: files(0) })); });
  it("reserves idempotently and refuses the UTC daily spend limit", async () => { const order = await makeOrder(); await readyImages(order); const next = await claimJob("test-worker"); assert.ok(next); process.env.PICTURE_DAILY_BUDGET_CENTS = "100"; await reserveSpend(next.job.id, next.job.leaseToken, 100); await reserveSpend(next.job.id, next.job.leaseToken, 100); assert.equal((await database.pool.query("SELECT SUM(cents)::int AS n FROM picture_spend")).rows[0].n, 100); const second = await claimJob("other-worker"); assert.ok(second); await assert.rejects(reserveSpend(second.job.id, second.job.leaseToken, 100), /ceiling/); });
  it("quarantines a crashed provider call without spending again", async () => { const order = await makeOrder(); await readyImages(order); const next = await claimJob("test-worker"); assert.ok(next); await reserveSpend(next.job.id, next.job.leaseToken, 100); await recordProviderStarted(next.job.id, next.job.leaseToken); await database.pool.query("UPDATE picture_jobs SET lease_until=now()-interval '1 second' WHERE id=$1", [next.job.id]); assert.equal(await claimJob("restarted-worker"), null); assert.equal((await getOrderInternal(order.id)).status, "paused"); assert.equal((await database.pool.query("SELECT state FROM picture_jobs WHERE id=$1", [next.job.id])).rows[0].state, "uncertain"); await assert.rejects(adminAction(order.id, "resume", "Retry"), /uncertain/); });
  it("hides files until owner release, then approves the final collection", async () => { const order = await makeOrder(); await produceCollection(order); const result = publicOrder(await getOrderInternal(order.id)); assert.equal(result.files.length, 10); assert.equal("path" in result.files[0], false); await reviewOrder(order.id, "approve", ""); assert.equal((await getOrderInternal(order.id)).status, "delivered"); });
  it("fulfills one reviewed scene revision within remaining spend and two total attempts", async () => { const order = await makeOrder(); await produceCollection(order); await reviewOrder(order.id, "revise", "Please make scene one brighter."); await adminAction(order.id, "revise_scene", "Minor lighting change approved.", { sceneIndex: 0, prompt: "Same subject and scene with brighter lighting", caption: "A brighter next chapter." }); const next = await claimJob("test-worker"); assert.ok(next); assert.equal(next.job.attempt, 2); await reserveSpend(next.job.id, next.job.leaseToken, 100); await recordProviderStarted(next.job.id, next.job.leaseToken); await completeImage(next.job.id, next.job.leaseToken, { files: files(0), actualCostCents: 20 }); await adminAction(order.id, "release", "Revision reviewed"); await assert.rejects(reviewOrder(order.id, "revise", "A second request"), /already been used/); });
  it("offers manual adjustments when a revision lacks generation budget", async () => { const order = await makeOrder(); await produceCollection(order, 100); await reviewOrder(order.id, "revise", "Adjust scene one."); await assert.rejects(adminAction(order.id, "revise_scene", "Reviewed", { sceneIndex: 0, prompt: "A cosmetic adjustment to the original scene", caption: "Caption" }), /budget/); await applyManualOutputs(order.id, 0, files(0)); assert.equal((await getOrderInternal(order.id)).status, "owner_review"); assert.equal((await database.pool.query("SELECT SUM(cents)::int AS n FROM picture_spend")).rows[0].n, 500); });
  it("manual reconciliation invalidates a leased revision and waits for other queued revisions", async () => {
    const order = await makeOrder(); await produceCollection(order); await reviewOrder(order.id, "revise", "Brighten scenes one and two.");
    for (const sceneIndex of [0, 1]) await adminAction(order.id, "revise_scene", "Reviewed lighting change", { sceneIndex, prompt: `Original composition ${sceneIndex} with a minor lighting adjustment`, caption: "A bright chapter." });
    const leased = await claimJob("test-worker"); assert.ok(leased); await reserveSpend(leased.job.id, leased.job.leaseToken, 100); await recordProviderStarted(leased.job.id, leased.job.leaseToken); await adminAction(order.id, "pause", "Team adjustment");
    await applyManualOutputs(order.id, leased.job.sceneIndex!, files(leased.job.sceneIndex!)); assert.equal((await getOrderInternal(order.id)).status, "paused"); await assert.rejects(adminAction(order.id, "release", "Ready"));
    await assert.rejects(completeImage(leased.job.id, leased.job.leaseToken, { files: files(leased.job.sceneIndex!) }), /lease/);
    await applyManualOutputs(order.id, leased.job.sceneIndex === 0 ? 1 : 0, files(leased.job.sceneIndex === 0 ? 1 : 0)); assert.equal((await getOrderInternal(order.id)).status, "owner_review"); await adminAction(order.id, "release", "Reviewed manual adjustments");
    assert.equal(await claimJob("test-worker"), null); await assert.rejects(heartbeatJob(leased.job.id, leased.job.leaseToken), /lease/);
  });
  it("does not queue a third attempt when a revised scene fails", async () => { const order = await makeOrder(); await produceCollection(order); await reviewOrder(order.id, "revise", "Scene one lighting"); await adminAction(order.id, "revise_scene", "Reviewed", { sceneIndex: 0, prompt: "The same scene with brighter light", caption: "Caption" }); const revision = await claimJob("test-worker"); assert.ok(revision); assert.equal(revision.job.attempt, 2); await failJob(revision.job.id, revision.job.leaseToken, "Provider refused this composition", { retryable: true }); assert.equal((await getOrderInternal(order.id)).status, "paused"); assert.equal(await claimJob("test-worker"), null); });
  it("never automatically retries an ambiguous request", async () => { const order = await makeOrder(); await readyImages(order); const next = await claimJob("test-worker"); assert.ok(next); await reserveSpend(next.job.id, next.job.leaseToken, 100); await recordProviderStarted(next.job.id, next.job.leaseToken); await failJob(next.job.id, next.job.leaseToken, "Connection lost", { ambiguous: true, retryable: true }); assert.equal(await claimJob("test-worker"), null); await assert.rejects(adminAction(order.id, "retry", "try again"), /No safe retry/); });
  it("keeps paid briefs valid and enforces durable request limits", async () => { const order = await makeOrder(); await pay(order); const next = await claimJob("test-worker"); assert.ok(next); await completePlan(next.job.id, next.job.leaseToken, plans(5)); await assert.rejects(updateBrief(order.id, { ...brief(), usesLikeness: true }), /reference photo/); await rateLimit("unit-test", 2, 60); await rateLimit("unit-test", 2, 60); await assert.rejects(rateLimit("unit-test", 2, 60), /Too many/); });
});
