"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import type { SalesReport, SalesMetricKey } from "@/lib/clientSalesTypes";
import { leadSourceLabel } from "@/lib/leadSourceLabel";

const metricLabels: Record<SalesMetricKey, string> = { callsMade: "Calls made", answeredCalls: "Connected calls", missedCalls: "Missed calls", discoveryCompleted: "Discoveries completed", proposalsSent: "Proposals sent" };
const date = (value: string) => Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString("en-US", { timeZone: "America/Chicago", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) + " CT" : "Time not recorded";
const count = (value: number | null) => value === null ? "—" : value.toLocaleString("en-US");
const heat: Record<string, number> = { hot: 100, proposal: 90, qualified: 80, call_booked: 70, contacted: 50, new: 30, won: 10, enrolled: 10, lost: 0, closed: 0 };
export default function ClientSalesWorkspace({ report, ownerAccess, initialClient = "leadflow" }: { report: SalesReport; ownerAccess: boolean; initialClient?: string }) {
  const router = useRouter();
  const clients = report.clients.filter(c => ownerAccess || c.key === "leadflow");
  const client = clients.find(c => c.key === initialClient) || clients[0];
  const [periodKey, setPeriodKey] = useState<"week" | "month" | "year">("week");
  const [sort, setSort] = useState("hot");
  const [page, setPage] = useState(1);
  const [callPage, setCallPage] = useState(1);
  const ordered = useMemo(() => [...(client?.opportunities || [])].sort((a, b) => (sort === "hot" ? (b.heat ?? heat[b.status] ?? 20) - (a.heat ?? heat[a.status] ?? 20) : 0) || (Date.parse(b.createdAt) || 0) - (Date.parse(a.createdAt) || 0) || a.id.localeCompare(b.id)), [client, sort]);
  if (!client) return <p className="p-6">Sales reporting is unavailable. Try again after the next source refresh.</p>;
  const period = client.periods[periodKey], pages = Math.max(1, Math.ceil(ordered.length / 15)), currentPage = Math.min(page, pages);
  const calls = client.calls.filter(call => Date.parse(call.at) >= Date.parse(period.start) && Date.parse(call.at) < Date.parse(period.end)).sort((a, b) => Date.parse(b.at) - Date.parse(a.at));
  const callPages = Math.max(1, Math.ceil(calls.length / 15)), currentCallPage = Math.min(callPage, callPages);
  function selectClient(key: string) { setPage(1); setCallPage(1); router.push(`/admin/sales/pipeline?client=${encodeURIComponent(key)}`); }
  const control = "min-h-[44px] rounded-lg border border-[var(--line)] bg-[var(--panel)] px-3 text-sm disabled:opacity-40";
  const clientIndex = clients.findIndex(c => c.key === client.key);
  return <section className="space-y-5 min-w-0" aria-label="Client sales workspace">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-flow-400">LeadFlow Pro · Sales</p><h1 className="mt-1 text-2xl font-semibold">{client.label}</h1><p className="text-xs text-[var(--muted)] mt-1">Source snapshot: {date(report.publishedAt)}</p><p className="text-xs text-[var(--muted)] mt-1">Open proposals: {count(client.openProposals ?? null)} · Current snapshot</p></div>
      <div className="flex items-center gap-2 max-w-full"><button className={control} disabled={clientIndex <= 0} onClick={() => selectClient(clients[clientIndex - 1].key)} aria-label="Previous client">←</button><label className="min-w-0"><span className="sr-only">Client</span><select className={`${control} max-w-full`} value={client.key} onChange={e => selectClient(e.target.value)}>{clients.map(c => <option key={c.key} value={c.key}>{c.label}</option>)}</select></label><button className={control} disabled={clientIndex >= clients.length - 1} onClick={() => selectClient(clients[clientIndex + 1].key)} aria-label="Next client">→</button></div>
    </header>
    {(client.message || client.coverage) && <div className="rounded-xl border border-[var(--line)] p-3 text-sm text-[var(--muted)]" role="status">{client.message}{client.coverage && <p>{client.coverage}</p>}</div>}
    <div className="flex flex-wrap items-center justify-between gap-2"><div className="flex gap-1" aria-label="Reporting period">{(["week", "month", "year"] as const).map(key => <button key={key} className={`${control} ${key === periodKey ? "border-cyan-400 text-cyan-400" : ""}`} aria-pressed={key === periodKey} onClick={() => {setPeriodKey(key);setCallPage(1);}}>{key[0].toUpperCase() + key.slice(1)}</button>)}</div><p className="text-xs text-[var(--muted)]">{period.label} · Compared with the same elapsed portion of the previous period</p></div>
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-5">{(Object.keys(metricLabels) as SalesMetricKey[]).map(key => {const metric = period.metrics[key];return <article className="rounded-xl border border-[var(--line)] bg-[var(--panel)] p-4" key={key}><h2 className="text-xs text-[var(--muted)]">{metricLabels[key]}</h2><p className="text-3xl font-semibold my-2 tabular-nums">{count(metric.value)}</p><p className="text-xs text-[var(--muted)]">Previous: {count(metric.previous)}{metric.delta !== null && <> · {metric.delta > 0 ? "+" : ""}{count(metric.delta)}</>}{metric.percent !== null ? <> ({metric.percent > 0 ? "+" : ""}{metric.percent.toFixed(1)}%)</> : metric.previous === 0 && metric.value !== null && metric.value > 0 ? " · No prior baseline" : null}</p>{metric.coverage && <p className="text-xs text-[var(--muted)] mt-2">{metric.coverage}</p>}</article>;})}</div>
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Opportunities <span className="text-sm text-[var(--muted)]">{client.status === "unavailable" ? "· Not connected" : `· ${ordered.length} shown`}</span></h2><label className="flex items-center gap-2 text-sm">Sort<select className={control} value={sort} onChange={e => {setSort(e.target.value);setPage(1);}}><option value="hot">Hottest first</option><option value="recent">Most recent</option></select></label></div>
    <div className="grid gap-3 lg:grid-cols-2">{ordered.slice((currentPage - 1) * 15, currentPage * 15).map(op => <article className="min-w-0 rounded-xl border border-[var(--line)] bg-[var(--panel)] p-4" key={op.id}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold break-words">{op.href ? <Link href={op.href} className="hover:underline">{op.name}</Link> : op.name}</h3><span className="text-xs text-[var(--muted)]">{op.status.replace(/_/g, " ")}</span></div>{op.businessName && <p className="text-sm text-[var(--muted)]">{op.businessName}</p>}<div className="flex flex-wrap items-center gap-3 mt-2"><span className="text-xs rounded-full border border-[var(--line)] px-2 py-1">{leadSourceLabel(op.source)}</span>{op.phone ? <a className="min-h-[44px] inline-flex items-center text-flow-400 text-sm" href={`tel:${op.phone.replace(/[^+\d]/g, "")}`}>{op.phone}</a> : <span className="text-xs text-[var(--muted)]">Phone not provided</span>}</div>{op.brief && <p className="text-sm mt-2 whitespace-pre-line break-words">{op.brief}</p>}<p className="text-xs mt-3 text-[var(--muted)]">Last recorded human touch: {op.lastTouch?.name || "Not recorded"}{op.lastTouch?.at && ` · ${date(op.lastTouch.at)}`}</p></article>)}</div>
    {!ordered.length && <p className="text-sm text-[var(--muted)]">{client.status === "unavailable" ? "Opportunity records are not connected for this client yet." : "No opportunities in the current source snapshot."}</p>}
    <nav className="flex items-center justify-between gap-2" aria-label="Opportunity pages"><button className={control} disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>Previous</button><span className="text-xs">Page {currentPage} of {pages} · 15 per page</span><button className={control} disabled={currentPage === pages} onClick={() => setPage(currentPage + 1)}>Next</button></nav>
    <section className="rounded-xl border border-[var(--line)] overflow-hidden"><h2 className="p-4 text-lg font-semibold">Call activity</h2><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="text-xs text-[var(--muted)]"><tr>{["When / contact", "Direction", "Status", "Duration", "Team member", "Outcome / source"].map(label => <th key={label} className="p-3 font-medium">{label}</th>)}</tr></thead><tbody>{calls.slice((currentCallPage - 1) * 15, currentCallPage * 15).map(call => <tr key={call.id} className="border-t border-[var(--line)]"><td className="p-3 whitespace-nowrap">{date(call.at)}{call.leadName && <p className="text-xs text-[var(--muted)]">{call.leadName}</p>}</td><td className="p-3">{call.direction}</td><td className="p-3">{call.status}</td><td className="p-3 whitespace-nowrap">{call.durationSeconds === null ? "Not recorded" : `${Math.floor(call.durationSeconds / 60)}m ${Math.round(call.durationSeconds % 60)}s`}</td><td className="p-3">{call.actor || "Not recorded"}</td><td className="p-3 min-w-[180px]">{call.outcome || "Outcome not recorded"}<p className="text-xs text-[var(--muted)]">{leadSourceLabel(call.source)}</p></td></tr>)}</tbody></table></div>{!calls.length && <p className="p-4 text-sm text-[var(--muted)]">No recorded calls available for this period. Check source coverage above.</p>}<nav className="p-3 flex justify-between items-center" aria-label="Call activity pages"><button className={control} disabled={currentCallPage === 1} onClick={() => setCallPage(currentCallPage - 1)}>Previous</button><span className="text-xs">{currentCallPage} / {callPages}</span><button className={control} disabled={currentCallPage === callPages} onClick={() => setCallPage(currentCallPage + 1)}>Next</button></nav></section>
  </section>;
}
