"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowUpRight, BookOpen, Boxes, ChevronRight, Expand, Factory, GraduationCap, Layers3, Pause, Play, Radio, ShieldCheck, Sparkles, Tractor, TrendingUp, Zap } from "lucide-react";
import { forecast, type ShowcaseData, type ModelInput } from "@/lib/showcaseData";
import "./showcase.css";
import { SHOWCASE_PROOF as PROOF } from "@/lib/site/showcaseProof";
const money = (n: number | null, decimals = 0) => n === null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: decimals }).format(n);
const compact = (n: number | null) => n === null ? "—" : new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 }).format(n);
const count = (n: number | null) => n === null ? "—" : Math.round(n).toLocaleString();
const DEFAULTS: Record<"dirt" | "education", ModelInput> = {
  dirt: { budget: 1500, cpl: 25, ticket: 4500, margin: 40, fee: 7000, convert: 27, repeat: 0, booking: 40, show: 75, enrollment: 30, capacity: 48 },
  education: { budget: 1500, cpl: 25, ticket: 3000, margin: 60, fee: 1000, convert: 27, repeat: 0, booking: 40, show: 75, enrollment: 30, capacity: 20 },
};

function SectorArt({ sector }: { sector: "dirt" | "education" }) {
  return <svg className="sector-art" viewBox="0 0 640 320" aria-hidden="true"><defs><linearGradient id="wire-light"><stop stopColor="#49dbff"/><stop offset="1" stopColor="#7568ff"/></linearGradient><filter id="wire-bloom"><feGaussianBlur stdDeviation="2"/></filter></defs><g className="wire-grid" fill="none" stroke="currentColor" opacity=".25">{Array.from({ length: 12 }, (_, i) => <path key={i} d={`M${i * 60 - 40},320 L320,120 L${i * 60 + 60},320`}/>)}{[180,200,230,270,310].map(y => <path key={y} d={`M0,${y}H640`}/>)}</g><g fill="none" stroke="url(#wire-light)" strokeWidth="2.2" strokeLinejoin="round">{sector === "dirt" ? <><path d="M145 210h275l24 26-17 30H133l-16-27z M160 224h252v27H153z M178 207v-71l58-19h59v91 M187 136h52v59h-52z M251 130h33v65h-33z M294 165l102-66 101 27 39 96 M392 101l14-13 98 25 38 112-27 23-29-7 20-35 M300 185h72l-16 23H299 M137 237h290"/><circle cx="165" cy="239" r="14"/><circle cx="219" cy="239" r="14"/><circle cx="272" cy="239" r="14"/><circle cx="326" cy="239" r="14"/><circle cx="379" cy="239" r="14"/><path d="M285 111l13-25 90-27 18 29 M515 244l45 15-8 21-48-4-17-20"/></> : <><path d="M126 223l188-47 197 45-182 58z M139 193l177-62 183 60-172 66z M182 201v-89l133-51 137 51v89 M176 112l138-55 145 55-142 56z M204 121v71 M245 138v65 M282 151v63 M351 152v63 M390 139v65 M428 123v72 M157 218v21l166 56 161-53v-19 M268 188v43 M283 188v43 M337 193v43 M352 191v43"/>{[204,245,283,351,392,429].map((x,i) => <path key={x} d={`M${x} ${i < 3 ? 121+i*15 : 151-(i-3)*14}l18-6v42l-18 6z`}/>)}</g><g className="art-scan"><path d="M80 175h480" stroke="#74ecff" opacity=".8"/><circle cx="320" cy="175" r="5" fill="#9cf5ff"/></g></svg>;
}
function Slider({ label, value, min, max, step = 1, onChange, prefix = "", suffix = "" }: { label: string; value: number; min: number; max: number; step?: number; onChange: (n: number) => void; prefix?: string; suffix?: string }) {
  return <label className="fx-control"><span>{label}<b>{prefix}{value.toLocaleString()}{suffix}</b></span><input type="range" aria-label={label} min={min} max={max} step={step} value={value} onChange={e => onChange(Number(e.target.value))}/></label>;
}
export default function Showcase({ data }: { data: ShowcaseData }) {
  const [industry, setIndustry] = useState<"dirt" | "education">("dirt");
  const [inputs, setInputs] = useState(DEFAULTS);
  const [tab, setTab] = useState<"forecast" | "proof">("forecast");
  const [paused, setPaused] = useState(false); const [selectedProof, setSelectedProof] = useState(0); const [clock, setClock] = useState(""); const [leaving, setLeaving] = useState(false);
  const root = useRef<HTMLDivElement>(null); const input = inputs[industry], model = forecast(industry, input), proof = PROOF[selectedProof];
  const put = (key: keyof ModelInput, n: number) => setInputs(x => ({ ...x, [industry]: { ...x[industry], [key]: n } }));
  useEffect(() => { const tick = () => setClock(new Date().toLocaleTimeString("en-US", { timeZone: "America/Chicago", hour12: false })); tick(); const id = setInterval(tick, 1000); return () => clearInterval(id); }, []);
  async function fullscreen() { if (!document.fullscreenElement) await root.current?.requestFullscreen?.(); else await document.exitFullscreen?.(); }
  const targetProgress = Math.min(100, (data.proposals.sharedValue || 0) / data.proposals.goal * 100);
  const sector = industry === "dirt" ? "DIRT WORKERS" : "EDUCATION";
  return <div ref={root} className={`fx-root fx-${industry} ${paused ? "fx-paused" : ""}`}>
    <div className="fx-atmosphere" aria-hidden="true"><div className="fx-mesh"/><div className="fx-orbit a"/><div className="fx-orbit b"/><div className="fx-grain"/></div>
    <header className="fx-header"><div className="fx-brand"><span className="fx-brand-mark"><img src="/admin-workspace/leadflow-logo.webp" alt="The LeadFlow Pro" width="54" height="54"/></span><div><strong>THE LEADFLOW PRO</strong><small>SPECIAL EFFECTS <i/> INDUSTRY COMMAND</small></div></div><div className="fx-header-center"><span className="fx-signal-dot"/> SYSTEM SHOWCASE <span className="fx-divider">/</span> {clock || "CHICAGO"} <small>CENTRAL</small></div><div className="fx-actions"><span className="fx-safe"><ShieldCheck size={13}/> CAMERA-SAFE</span><button onClick={() => setPaused(!paused)} aria-label={paused ? "Resume motion" : "Pause motion"}>{paused ? <Play size={17}/> : <Pause size={17}/>}</button><button onClick={fullscreen} aria-label="Toggle fullscreen"><Expand size={17}/></button><button onClick={() => setLeaving(true)} aria-label="Return to private workspace"><ArrowLeft size={17}/></button></div></header>
    <div className="fx-topline"><span><Radio size={13}/> ANONYMOUS INDUSTRIES · CUSTOMER IDENTITIES EXCLUDED</span><span>HISTORICAL PROOF <i/> VERIFIED SNAPSHOT <i/> INTERACTIVE FORECASTS</span></div>
    <main className="fx-layout">
      <aside className="fx-left"><div className="fx-section-label">SELECT YOUR SECTOR <span>01 / 02</span></div><button className={`fx-sector ${industry === "dirt" ? "active" : ""}`} onClick={() => setIndustry("dirt")}><Tractor size={24}/><div><b>DIRT WORKERS</b><small>Land clearing · excavation · hauling</small></div><ChevronRight size={16}/></button><button className={`fx-sector ${industry === "education" ? "active" : ""}`} onClick={() => setIndustry("education")}><GraduationCap size={24}/><div><b>EDUCATION</b><small>Schools · training · online programs</small></div><ChevronRight size={16}/></button>
        <div className="fx-panel fx-opportunity"><span className="fx-kicker">THE OPPORTUNITY ENGINE</span><div className="fx-ring" style={{ "--progress": `${targetProgress}%` } as React.CSSProperties}><svg viewBox="0 0 180 180" aria-hidden="true"><circle cx="90" cy="90" r="74"/><circle className="progress" cx="90" cy="90" r="74" pathLength="100" strokeDasharray={`${targetProgress} 100`}/></svg><div><small>SHARED PROPOSALS</small><b>{compact(data.proposals.sharedValue)}</b><span>{targetProgress.toFixed(0)}% of $100K goal</span></div></div><div className="fx-small-pairs"><div><strong>{count(data.proposals.shared)}</strong><small>documented shares</small></div><div><strong>{count(data.proposals.reviewed)}</strong><small>reviews held</small></div><div><strong>{compact(data.proposals.openValue)}</strong><small>prepared pipeline</small></div></div><p>Proposal value is tracked separately from accepted sales and collected payments.</p></div>
        <div className="fx-panel fx-agency"><div className="fx-section-label">AGENCY DEMAND <span>28 DAYS</span></div><div className="fx-agency-cpl"><strong>{money(data.agency.cpl,2)}</strong><span>verified agency CPL</span></div><div className="fx-small-pairs"><div><strong>{count(data.agency.leads)}</strong><small>Meta lead actions</small></div><div><strong>{money(data.agency.spend)}</strong><small>ad spend</small></div></div><p>LeadFlow’s own campaign. Client job and enrollment acquisition are separate metrics.</p></div>
      </aside>
      <section className="fx-center"><div className="fx-view-heading"><div><span className="fx-kicker">{sector} / OPPORTUNITY INTELLIGENCE</span><h1>{industry === "dirt" ? <>Turn demand<br/>into <em>real work.</em></> : <>Turn interest<br/>into <em>enrollments.</em></>}</h1></div><div className="fx-mode-tabs"><button className={tab === "forecast" ? "active" : ""} onClick={() => setTab("forecast")}><Zap size={13}/> FORECAST LAB</button><button className={tab === "proof" ? "active" : ""} onClick={() => setTab("proof")}><Layers3 size={13}/> RESULTS VAULT</button></div></div>
        {tab === "forecast" ? <><div className="fx-stage"><div className="fx-stage-label"><span>MODEL / {industry === "dirt" ? "90-DAY PLANNING HORIZON" : "MONTHLY COHORT"}</span><b><Sparkles size={12}/> ADJUST THE INPUTS. SEE THE IMPACT.</b></div><div className="fx-core"><div className="fx-core-ring one"/><div className="fx-core-ring two"/><div className="fx-core-ring three"/><div className="fx-core-number"><span>PROJECTED {industry === "dirt" ? "CAMPAIGN JOBS" : "ENROLLMENT REVENUE"}</span><strong>{industry === "dirt" ? model.totalJobs : compact(model.revenue)}</strong><small>{industry === "dirt" ? `${model.units} first jobs + ${model.totalJobs - model.units} repeat jobs` : `${model.units} modeled enrollments · ${money(input.ticket)} program price`}</small></div></div><SectorArt sector={industry}/><div className="fx-stage-edges"><span>DEMAND → CONVERSION → {industry === "dirt" ? "JOBS" : "ENROLLMENTS"}</span><span>SCENARIO VISUALIZATION</span></div></div>
          <div className="fx-value-grid"><article className="fx-value-card"><span>PROJECTED REVENUE</span><b>{compact(model.revenue)}</b><small>{industry === "dirt" ? "First + repeat jobs" : "Modeled enrollment value"}</small><div className="fx-value-line"/></article><article className="fx-value-card primary"><span>AFTER CAMPAIGN COSTS</span><b className={model.contribution < 0 ? "negative" : ""}>{compact(model.contribution)}</b><small>Margin contribution less ads + fee</small><div className="fx-value-line"/></article><article className="fx-value-card"><span>MODELED ROI</span><b className={model.roi !== null && model.roi < 0 ? "negative" : ""}>{model.roi === null ? "—" : Math.round(model.roi) + "%"}</b><small>Contribution ÷ acquisition investment</small><div className="fx-value-line"/></article></div>
          <div className="fx-flow">{[["01","INQUIRIES",Math.floor(model.leads)],["02",industry === "dirt" ? "CONVERSATIONS" : "APPOINTMENTS",Math.floor(model.appointments)],["03",industry === "dirt" ? "NEW CUSTOMERS" : "ENROLLMENTS",model.units],["04",industry === "dirt" ? "TOTAL JOBS" : "COHORT VALUE",industry === "dirt" ? model.totalJobs : compact(model.revenue)]].map(([n,label,value]) => <div className="fx-flow-node" key={String(n)}><span>{n}</span><b>{value}</b><small>{label}</small></div>)}</div>
        </> : <div className={`fx-proof-feature tone-${proof.color}`}><div className="fx-proof-crown"><Factory size={19}/><span>HISTORICAL TEAM EXPERIENCE</span><span className="fx-proof-tag">CLIENT-REPORTED</span></div><p className="fx-kicker">{proof.industry}</p><strong className="fx-proof-number">{proof.value}</strong><h2>{proof.unit}</h2><div className="fx-proof-signal"><TrendingUp size={20}/>{proof.signal}</div><p className="fx-proof-detail">{proof.detail}</p><div className="fx-proof-spectrum" aria-hidden="true">{Array.from({length:24},(_,i) => <i key={i} style={{height:`${18+((i*17)%83)}%`,animationDelay:`${i*.08}s`}}/>)}</div><p className="fx-proof-note">Historical personal/team experience. These statements describe their original context; current campaign metrics and forecasts remain separate.</p></div>}
        <div className="fx-evidence-strip"><span><ShieldCheck size={13}/> VERIFIED CLIENT {industry === "dirt" ? "JOB" : "ENROLLMENT"} METRICS</span><b>CPL {money(data.clientMetrics[industry].cpl,2)}</b><b>CPA {money(data.clientMetrics[industry].cpa,2)}</b><small>{data.clientMetrics[industry].cpl === null ? "Acquisition evidence awaits verification" : "Observed campaign snapshot"}</small></div>
      </section>
      <aside className="fx-right"><div className="fx-section-label">{tab === "forecast" ? "SCENARIO CONTROLS" : "SELECT A RESULTS SECTOR"}<span>{tab === "forecast" ? "MODEL INPUTS" : "ANONYMOUS PROOF"}</span></div>{tab === "forecast" ? <div className="fx-panel fx-controls"><div className="fx-control-heading"><Boxes size={18}/><span>Shape the opportunity.</span><button onClick={() => setInputs(x => ({ ...x, [industry]: DEFAULTS[industry] }))}>RESET</button></div><Slider label="Ad budget" value={input.budget} min={0} max={10000} step={100} prefix="$" onChange={n => put("budget",n)}/><Slider label="Assumed cost per lead" value={input.cpl} min={5} max={150} step={1} prefix="$" onChange={n => put("cpl",n)}/><Slider label={industry === "dirt" ? "Average job value" : "Average program price"} value={input.ticket} min={500} max={20000} step={100} prefix="$" onChange={n => put("ticket",n)}/><Slider label="Gross margin assumption" value={input.margin} min={5} max={80} suffix="%" onChange={n => put("margin",n)}/>{industry === "dirt" ? <><Slider label="Lead-to-first-job conversion" value={input.convert} min={1} max={60} suffix="%" onChange={n => put("convert",n)}/><Slider label="Follow-on jobs · same customers" value={input.repeat} min={0} max={24} onChange={n => put("repeat",n)}/><div className="fx-fixed-fee"><span>Contractor service package</span><b>$7,000</b><small>16-first-job objective · creative included</small></div></> : <><Slider label="Lead-to-appointment rate" value={input.booking} min={5} max={80} suffix="%" onChange={n => put("booking",n)}/><Slider label="Appointment show-up rate" value={input.show} min={10} max={100} suffix="%" onChange={n => put("show",n)}/><Slider label="Attendee-to-enrollment rate" value={input.enrollment} min={5} max={80} suffix="%" onChange={n => put("enrollment",n)}/><Slider label="Service fee · scenario input" value={input.fee} min={0} max={7000} step={100} prefix="$" onChange={n => put("fee",n)}/></>}
          <Slider label={industry === "dirt" ? "90-day job capacity" : "Available cohort seats"} value={input.capacity} min={1} max={200} onChange={n => put("capacity",n)}/><div className="fx-acquisition"><div><span>MODELED AD CPA</span><b>{money(model.cpa)}</b></div><div><span>FULL ACQUISITION COST</span><b>{money(model.cac)}</b></div><small>{industry === "dirt" ? "Uses first jobs/new customers. Repeat jobs add value without being counted as new acquisitions." : "Uses modeled enrollments. Tuition booked and payments collected remain distinct."}</small></div><div className="fx-break-even"><BookOpen size={15}/><span>Modeled break-even: <b>{model.breakEven === null ? "—" : model.breakEven} {industry === "dirt" ? "jobs" : "enrollments"}</b></span></div></div> : <div className="fx-proof-list">{PROOF.map((p,i) => <button key={p.id} className={selectedProof===i?"active":""} onClick={()=>setSelectedProof(i)}><span>{String(i+1).padStart(2,"0")}</span><div><b>{p.industry}</b><small>{p.value} · {p.unit}</small></div><ArrowUpRight size={14}/></button>)}</div>}</aside>
    </main>
    <footer className="fx-footer"><span><ShieldCheck size={12}/> NO CLIENT NAMES · NO CONTACT DETAILS · NO PRIVATE NOTES</span><p>{tab === "forecast" ? "SCENARIO ESTIMATES · Inputs are assumptions. Other operating overhead remains separate. Campaign settings stay unchanged." : "HISTORICAL, CLIENT-REPORTED EXPERIENCE · No names, faces or client-company identities displayed."}</p><span>{data.freshness === "stale" ? "HISTORICAL SNAPSHOT" : "SOURCE SNAPSHOT"} {data.asOf ? new Date(data.asOf).toLocaleDateString("en-US",{timeZone:"America/Chicago",month:"short",day:"numeric"}) : "UNAVAILABLE"}</span></footer>
    {leaving && <div className="fx-leave"><div><ShieldCheck size={30}/><h2>Return to the private workspace?</h2><p>Stop recording before leaving. The normal workspace contains private client information.</p><button onClick={()=>setLeaving(false)}>Stay in showcase</button><a href="/admin/overview">Return to workspace</a></div></div>}
  </div>;
}
