/** Source-approved historical testimonial claims. These are client-reported outcomes in their original markets, separate from current offer pricing. */
export const PROOF_STORIES = [
  { id: "scott", coverTitle: ["ONE JOB.", "REAL RESULTS."], name: "Scott Offerle", duration: "2:19", context: "Current LeadFlow client / O-L Guy Farms", title: "Hear how the work began.", summary: "Scott discusses his first project, operating costs and a follow-on inquiry in his own words." },
  { id: "stewman-funnels", coverTitle: ["HUNDREDS", "OF FUNNELS."], name: "Ryan Stewman", duration: "1:49", context: "Past funnel work with Patrick", title: "Years of building together.", summary: "Ryan describes years of funnel work, teamwork and attention to his goals." },
  { id: "katrina", coverTitle: ["SIX-FIGURE", "OFFER IMPACT."], name: "Katrina Ruth", duration: "4:13", context: "Past offer and advisory work with Patrick", title: "Finding the next move.", summary: "Katrina describes how one conversation helped her launch a mastermind she says generates hundreds of thousands annually." },
  { id: "glenn", coverTitle: ["CLARITY.", "CONFIDENCE."], name: "Glenn Smith", duration: "2:57", context: "Past coaching and business support", title: "Clarity on what comes next.", summary: "Glenn describes the support and clarity he experienced while building his coaching business." },
  { id: "blake", coverTitle: ["27 LEADS.", "4 PROSPECTS."], name: "Blake", duration: "0:28", context: "Earlier real estate campaign", title: "From inquiry to conversation.", summary: "An earlier client reported 27 leads and four active conversations—not four completed sales." },
  { id: "jason", coverTitle: ["FIRST DEAL.", "~6 WEEKS."], name: "Jason Sammons", duration: "0:32", context: "Earlier real estate campaign", title: "The story of a first deal.", summary: "Jason described his first deal in about six weeks in an earlier real estate campaign." },
  { id: "luke", coverTitle: ["$70K+", "IN REVENUE."], name: "Luke Dreyer", duration: "0:46", context: "Historical campaign experience", title: "A client’s campaign experience.", summary: "Luke reports over $70,000 in revenue from just under $5,000 in ad spend in a past campaign; revenue is not profit." },
  { id: "murphy", coverTitle: ["$250K+", "PER MONTH."], name: "Bill Murphy", duration: "1:03", context: "Historical company growth", title: "An early member of the team.", summary: "Bill describes company growth to over $250,000 in monthly business, with Patrick as an original team member." },
  { id: "stewman-personal", coverTitle: ["REAL GRIT.", "REAL GROWTH."], name: "Ryan Stewman", duration: "2:52", context: "Historical personal reference", title: "Experience and commitment.", summary: "A historical personal reference about Patrick’s growth, experience and commitment." },
] as const;
