/** Public aggregate proof. Payment collections and client-reported project figures are distinct measures. */
export const RESULTS_PROOF = {
  scott: {
    business: "O-L Guy Farms",
    person: "Scott Offerle",
    figure: "≈$4,500",
    duration: "Reported job profit",
    label: "Approximate campaign figures",
    costNote: "Approximate reported figures. Advertising was approximately $300 separately; $500 is service cost, not total acquisition cost. Scott’s job-profit estimate comes from his interview.",
    cost: "≈$500",
    costLabel: "Service cost",
    situation: "After losing two $50,000 clients, Scott needed a new way to bring in worthwhile jobs.",
    image: "/images/case-briefs/earthmoving-results-20261008.png",
    imageAlt: "Illustrated earthmoving campaign artwork",
    summary: "About $500 in service cost for a job with approximately $4,500 reported profit; advertising was approximately $300 separately.",
    disclosure: "The starting account of two lost $50,000 clients was supplied by Patrick. Scott describes approximately $4,500 in job profit in his interview at 00:16–00:22; he later recalls a slightly different amount. At 00:32–00:48 he separates $500 in service cost from roughly $300 in advertising. These are client recollections, not audited financial statements; the profit accounting basis is not independently verified.",
  },
  premier: {
    business: "Premier Dental Academy",
    image: "/images/case-briefs/dental-enrollment-results-20261008.png",
    imageAlt: "Illustrated dental training campaign artwork",
    months: [
      { label: "August 2026", display: "$4,466", cents: 446600, firstPayers: 6 },
      { label: "September 2026", display: "$15,264", cents: 1526400, firstPayers: 8 },
    ],
    increase: "+242%",
    cost: "≈$352",
    value: "$3,000",
    ratio: "8.5×",
    situation: "A hands-on dental school needs the right students to turn interest into paid enrollment.",
    economicsNote: "Approximate campaign acquisition cost supplied by Patrick. $3,000 tuition ÷ $352 acquisition cost ≈ 8.5×. Tuition value, not profit; this is separate from the Square collections below.",
    julyContext: "July collections were $18,464 after recorded refunds, higher than September. This comparison describes two months, not a steady upward trend.",
    unmatchedContext: "September includes one unmatched customer’s $150 payment in collections. That customer is excluded from the student count.",
    asOf: "October 8, 2026",
    ownership: "Premier Dental Academy and The LeadFlow Pro share common ownership. Amanda leads the school; this is an operating example from the same group.",
  },
  luke: {
    business: "Luke Dreyer",
    image: "https://sites.theleadflowpro.com/_proof/20261006-v1/assets/luke-reference.jpg",
    imageAlt: "Luke Dreyer in his testimonial",
    situation: "Luke, a CFO working with a tax attorney, describes a campaign to bring in valuable tax-service work.",
    cost: "≈$714",
    value: "$10,000",
    ratio: "14×",
    originalNumbers: "Over $70,000 revenue · Under $5,000 ad spend",
    costNote: "About $714 ad spend per $10,000 in revenue, using rounded testimonial figures. Historical Patrick campaign; not average client acquisition cost or profit.",
    disclosure: "Luke’s testimonial reports more than $70,000 in revenue on just under $5,000 in advertising. Using those rounded reference amounts, $5,000 ÷ $70,000 × $10,000 ≈ $714 in ad spend per $10,000 in revenue; $70,000 ÷ $5,000 = 14× revenue to ad spend. This calculation expresses advertising spend at a $10,000 revenue benchmark. It does not establish a customer count or profit and excludes any costs other than the reported advertising. This is Patrick’s historical campaign experience with a tax-service business.",
  },
} as const;
