export type LeadFlowComponentRegistryItem = {
  name: string;
  path: string;
  purpose: string;
  props: string[];
  figmaName: string;
  variants?: string[];
  requiredStates?: string[];
  pagesUsing: string[];
  codeConnectNotes: string;
};

export const leadFlowComponentRegistry: LeadFlowComponentRegistryItem[] = [
  {
    name: "Button",
    path: "src/components/ui/button.tsx",
    purpose: "Primary shared CTA primitive for links and form actions.",
    props: ["variant", "href", "disabled", "type", "className", "children"],
    figmaName: "Component/Button",
    variants: ["primary", "secondary", "ghost", "outline", "danger", "premium"],
    requiredStates: ["default", "hover", "focus-visible", "disabled"],
    pagesUsing: ["/", "/marketplace", "/tools", "/submit-source", "/privacy-center", "/dashboard"],
    codeConnectNotes: "Map Figma Variant to variant and Text to children. Do not add ad hoc CTA classes on pages.",
  },
  {
    name: "MarketplaceCard",
    path: "src/components/marketplace/index.ts",
    purpose: "Buyer-facing lead signal listing preview with score, confidence, proof, and release status.",
    props: [
      "title",
      "category",
      "score",
      "confidence",
      "sourceType",
      "bestBuyer",
      "sampleCount",
      "proofStatus",
      "suppressionStatus",
      "lastUpdated",
      "variant",
      "href",
      "locked",
      "adminOnly",
    ],
    figmaName: "Component/MarketplaceCard",
    variants: ["compact", "full", "featured", "locked", "buyer_approved", "admin"],
    requiredStates: ["default", "locked", "buyer approved", "admin", "focus-visible"],
    pagesUsing: ["/marketplace", "/buy-leads", "/buyer/access", "/dashboard"],
    codeConnectNotes: "Use real prop names only. Figma Locked maps to locked, Admin maps to adminOnly.",
  },
  {
    name: "ScoreBadge",
    path: "src/components/ui/badge.tsx",
    purpose: "0 to 100 score badge with plain status level.",
    props: ["score", "variant", "label", "className"],
    figmaName: "Component/ScoreBadge",
    variants: ["high", "medium", "low", "unknown"],
    requiredStates: ["high", "medium", "low", "unknown"],
    pagesUsing: ["/marketplace", "/lead-profile/[id]", "/dashboard", "/tools"],
    codeConnectNotes: "Map Figma Score number to score. Variant can be omitted when code should infer level from score.",
  },
  {
    name: "ConfidenceBadge",
    path: "src/components/ui/badge.tsx",
    purpose: "Confidence label for proof depth and scoring reliability.",
    props: ["confidence", "label", "className"],
    figmaName: "Component/ConfidenceBadge",
    variants: ["high", "medium", "low", "needs_review"],
    requiredStates: ["high", "medium", "low", "needs review"],
    pagesUsing: ["/marketplace", "/lead-profile/[id]", "/dashboard"],
    codeConnectNotes: "Map Figma Confidence enum to confidence. Keep needs_review spelling in code.",
  },
  {
    name: "StatusBadge",
    path: "src/components/ui/badge.tsx",
    purpose: "Lifecycle and review status label.",
    props: ["status", "label", "className"],
    figmaName: "Component/StatusBadge",
    variants: ["submitted", "review", "approved", "rejected", "suppressed", "sold", "sample_available", "pending_access"],
    requiredStates: ["submitted", "review", "approved", "rejected", "suppressed", "sold", "sample available", "pending access"],
    pagesUsing: ["/marketplace", "/lead-profile/[id]", "/dashboard", "/buyer"],
    codeConnectNotes: "Use for lifecycle status. Suppression-specific copy can use SuppressionStatusBadge.",
  },
  {
    name: "SourceProofChip",
    path: "src/components/ui/badge.tsx",
    purpose: "Proof-first chip for public source, submitted source, or verified evidence context.",
    props: ["label", "verified", "className"],
    figmaName: "Component/SourceProofChip",
    variants: ["verified", "unverified"],
    requiredStates: ["verified", "unverified"],
    pagesUsing: ["/marketplace", "/profile-model", "/lead-profile/[id]", "/dashboard/source-submissions"],
    codeConnectNotes: "Map Figma Verified boolean to verified. Label must stay source-context only, never raw private data.",
  },
  {
    name: "SuppressionStatusBadge",
    path: "src/components/ui/badge.tsx",
    purpose: "Visible suppression and review-gated release status.",
    props: ["status", "label", "className"],
    figmaName: "Component/SuppressionBadge",
    variants: ["submitted", "review", "approved", "suppressed", "pending_access"],
    requiredStates: ["clear", "review", "suppressed", "pending access"],
    pagesUsing: ["/marketplace", "/lead-profile/[id]", "/privacy-center", "/dashboard"],
    codeConnectNotes: "Use for suppression-aware surfaces so buyers see restriction state before requesting data.",
  },
  {
    name: "BuyerPathCard",
    path: "src/components/leadflow/index.ts",
    purpose: "Homepage and router card for buyer, builder, submit-source, and tool lanes.",
    props: ["title", "body", "href", "icon", "proof", "className"],
    figmaName: "Component/BuyerPathCard",
    variants: ["default"],
    requiredStates: ["default", "hover", "focus-visible"],
    pagesUsing: ["/", "/buy-leads", "/build-my-system"],
    codeConnectNotes: "Figma Title, Body, Proof map directly. Icon should remain an instance swap in Figma.",
  },
  {
    name: "ToolCard",
    path: "src/components/leadflow/index.ts",
    purpose: "Public tool catalog card that shows answer, audience, time, data category, and CTA.",
    props: ["title", "who", "answer", "time", "dataCategory", "href"],
    figmaName: "Component/ToolCard",
    variants: ["default"],
    requiredStates: ["default", "hover", "focus-visible"],
    pagesUsing: ["/tools", "/industries/[slug]"],
    codeConnectNotes: "Figma text properties map directly. Tool cards must not collect data by themselves.",
  },
  {
    name: "ConsentModule",
    path: "src/components/forms/index.ts",
    purpose: "Reusable consent disclosure and action block.",
    props: ["title", "body", "bullets", "status", "ctaLabel", "className"],
    figmaName: "Component/ConsentModule",
    variants: ["review", "approved", "suppressed", "submitted"],
    requiredStates: ["unchecked", "checked", "saving", "saved", "error"],
    pagesUsing: ["/privacy-center", "/tools", "/submit-source"],
    codeConnectNotes: "Do not bury consent. Map state variants separately from content variants in Figma.",
  },
  {
    name: "AdminDataTable",
    path: "src/components/dashboard/admin-data-table.tsx",
    purpose: "Admin review table shell for profiles, sources, requests, exports, and events.",
    props: ["title", "columns", "rows", "className"],
    figmaName: "Component/AdminDataTable",
    variants: ["default", "empty", "loading"],
    requiredStates: ["default", "empty", "loading", "filtered"],
    pagesUsing: ["/dashboard", "/dashboard/exports", "/dashboard/source-submissions"],
    codeConnectNotes: "Rows are slot-like in design. Code rows must be pre-filtered server-side or client-side before render.",
  },
  {
    name: "LeadProfileHeader",
    path: "src/components/leadflow/index.ts",
    purpose: "Protected profile intelligence header with score, confidence, proof, suppression, and review badges.",
    props: ["title", "category", "vertical", "score", "confidence", "sourceStatus", "suppressionStatus", "reviewStatus"],
    figmaName: "Component/LeadProfileHeader",
    variants: ["buyer", "admin", "locked"],
    requiredStates: ["buyer", "admin", "locked", "suppressed"],
    pagesUsing: ["/lead-profile/[id]"],
    codeConnectNotes: "Do not expose raw contact or hidden answer fields through header props.",
  },
  {
    name: "ExportConfirmModal",
    path: "src/components/dashboard/export-confirm-modal.tsx",
    purpose: "Controlled export confirmation surface with visible field groups and audit warning.",
    props: ["title", "body", "fieldGroups"],
    figmaName: "Component/ExportConfirmModal",
    variants: ["buyer", "admin", "blocked"],
    requiredStates: ["default", "confirming", "blocked", "complete"],
    pagesUsing: ["/buyer/exports", "/dashboard/exports"],
    codeConnectNotes: "Figma field groups should map to approved group labels only, never raw field lists with PII.",
  },
];
