export const leadFlowDesignTokens = {
  color: {
    background: "#050918",
    surface: "#060A11",
    surfaceElevated: "#0B1017",
    border: "rgba(255,255,255,0.12)",
    mutedBorder: "rgba(255,255,255,0.08)",
    textPrimary: "#FFFFFF",
    textSecondary: "#CBD5E1",
    textMuted: "#94A3B8",
    primaryCta: "#FFD66B",
    secondaryCta: "#23B8FF",
    success: "#A6E36B",
    warning: "#FFD66B",
    danger: "#F87171",
    verified: "#5CD0FF",
    review: "#FFBA3D",
    suppressed: "#FB7185",
    premium: "#D946EF",
    neutral: "#94A3B8",
  },
  typography: {
    heroHeadline: { fontSize: "64px", lineHeight: "1.0", fontWeight: 900 },
    sectionHeadline: { fontSize: "40px", lineHeight: "1.05", fontWeight: 900 },
    cardTitle: { fontSize: "24px", lineHeight: "1.15", fontWeight: 900 },
    metricNumber: { fontSize: "40px", lineHeight: "1.0", fontWeight: 900 },
    body: { fontSize: "16px", lineHeight: "1.65", fontWeight: 500 },
    small: { fontSize: "14px", lineHeight: "1.55", fontWeight: 600 },
    badge: { fontSize: "12px", lineHeight: "1", fontWeight: 800 },
    tableHeader: { fontSize: "12px", lineHeight: "1.2", fontWeight: 800 },
    formLabel: { fontSize: "12px", lineHeight: "1.2", fontWeight: 800 },
    helperText: { fontSize: "12px", lineHeight: "1.45", fontWeight: 600 },
  },
  spacing: {
    4: "4px",
    8: "8px",
    12: "12px",
    16: "16px",
    24: "24px",
    32: "32px",
    48: "48px",
    64: "64px",
    96: "96px",
  },
  radius: {
    small: "4px",
    medium: "6px",
    large: "8px",
    card: "8px",
    pill: "999px",
    modal: "12px",
  },
  shadow: {
    panel: "inset 0 1px 0 rgba(255,255,255,0.06), 0 22px 54px -36px rgba(92,208,255,0.54)",
    cta: "inset 0 1px 0 rgba(255,255,255,0.62), 0 18px 36px -17px rgba(255,154,31,0.92)",
    dashboard: "inset 0 1px 0 rgba(255,255,255,0.08), 0 32px 90px -56px rgba(92,208,255,0.60)",
  },
} as const;

export type LeadFlowDesignTokens = typeof leadFlowDesignTokens;

export const leadFlowFigmaNames = {
  button: "Component/Button",
  badge: "Component/Badge",
  scoreBadge: "Component/ScoreBadge",
  confidenceBadge: "Component/ConfidenceBadge",
  statusBadge: "Component/StatusBadge",
  sourceProofChip: "Component/SourceProofChip",
  suppressionBadge: "Component/SuppressionBadge",
  riskBadge: "Component/RiskBadge",
  buyerPathCard: "Component/BuyerPathCard",
  marketplaceCard: "Component/MarketplaceCard",
  listingPreviewModal: "Component/ListingPreviewModal",
  leadProfileHeader: "Component/LeadProfileHeader",
  scoreBreakdownCard: "Component/ScoreBreakdownCard",
  sourceProofList: "Component/SourceProofList",
  buyerRequestForm: "Component/BuyerRequestForm",
  toolCard: "Component/ToolCard",
  questionnaireStep: "Component/QuestionnaireStep",
  progressIndicator: "Component/ProgressIndicator",
  adminDataTable: "Component/AdminDataTable",
  adminStatCard: "Component/AdminStatCard",
  filterBar: "Component/FilterBar",
  searchInput: "Component/SearchInput",
  emptyState: "Component/EmptyState",
  loadingState: "Component/LoadingState",
  errorState: "Component/ErrorState",
  consentModule: "Component/ConsentModule",
  exportConfirmModal: "Component/ExportConfirmModal",
} as const;
